### ISSUE TITLE
Case sensitivity in phrasal search

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#104]
After a bit of testing, I think we should turn on case-sensitivity for phrasal searches. It does make a big difference to the results -- searching for "humble servant" on ColDesp gets 3575 hits right now, but only 552 with case-sensitivity turned on; the rest are "humble Servant". But if you do this:

"humble [Ss]ervant"

you get over 3,000. What you can't do is this:

"[Hh]umble [Ss]ervant"

and I guess the reason is that neither of these words matches any of the wordlist items, since those matches are being done based on stemming the input word. So for a working search, you need at least the first non-stopword form to be free of wildcards in order to initiate a search at all. So the situation is:

 - We can turn on case-sensitivity with some obvious impact on search results; users will need to get case right to find things;
 - However, they can mitigate that problem by using wildcards; but
 - The first non-stopword term in a phrasal search must be free of wildcards otherwise it will not match to the wordlist, meaning that the JS search object will assume their can be no matches and retrieve nothing.

Options: 

1. Live with this; specify that exact phrase searches are case-sensitive, and avoid suggesting the use of wildcards in phrasal searches, because it's difficult to explain why they will sometimes work and sometimes not.
2. Try to treat the first non-stopword term as a regex when comparing it to the wordString; then stem the match in the wordstring. This might be tricky because many matches are possible for an asterisk wildcard, but we could limit the number of allowed hits.
3. Don't stop at the first non-stopword term in the index when it has wildcards; instead, use the first non-wildcard non-stopword term (which means we would have to insist that there is one -- so a phrasal search consisting only of wildcard terms and stopword items would result in an error message saying it's too broad).
4. A combination of 2 and 3, whereby we try to find a non-wildcard non-stopword term to use; if we fail, but there are wildcard terms, we start by preferring those using character classes rather than actual asterisks or question marks, and match them as regexes against the wordlist. If we find too many matches, we move on to another wildcard option; if/when we find a wildcard term that has a reasonable number of matches in the wordlist, we use that, but if we never get there, we show an error message to the effect that the search is too broad.

Thoughts?

If we do find a solution here, we should then be able to treat words beginning with capital letters as special one-term phrasal searches, which would enable precise searching for names.

**Comment by joeytakeda** [comment]
Thanks for laying this out! However, unless I’ve missed something, I thought we didn’t allow wildcards in phrasal searches: https://github.com/projectEndings/staticSearch/issues/48#issuecomment-612484539. And I don’t think we really should, especially if we match the exact phrasal punctuation, since then we’d need to explain that people must escape wildcards when wildcard searching is available (of course, some projects may turn off wildcards but enable phrasal). 

Of course, that sort of exact phrasal searching might not cut it for a project, since they may not care about differences in punctuation or capitalization. So my suggestion is that we do something like so:

* Keep the current behavior of looking for the first non-stopword term (since I think that works quite nicely and makes sense)
* Modify how exact phrases are matched slightly: rather than create the matching regex for exact phrases as an embedded process, turn that into a function in the Javascript, so that it could be more easily overriden. But by default, that function would expand all apostrophes and quotation marks to their curly/straight variants, but otherwise leave the phrase untouched (and be case sensitive). 
* If we wanted to, we could add configuration options for common things (maybe as attributes on phrasalSearch: `@caseSensitive=true|false` `@stripPunctuation=true|false`). That way, any people wanting to keep the current behavior of exact phrase matching (false, true, respectively) would be able to do so. People needing more complicated ways of massaging an exact phrase could implement that expansion. 

Does that seem like a reasonable solution?

**Comment by martindholmes** [comment]
We use wildcards in our phrasal searches because we expand the single apostrophe to wildcards, and it appears from my testing that even if we thought we were escaping e.g. square brackets, that isn't actually happening (although please test with your own projects to see if I'm absolutely right there).

The problem with letting people turn off case sensitivity is that we then can't use it for name-searching, which was the reason we went down this rabbit hole in the first place. The idea was that we want to get rid of the upper-case index, but if we do that, we either abandon any notion that people can search for names preferentially, or we use the phrasal mechanism to search for them; if the latter, then we need to make the phrasal mechanism case-sensitive; and in that case, ideally, we let people override that by using character classes; therefore we need to support wildcards in phrasal searches. That was my logic, and the main idea was that even though this adds greater sensitivity and precision, it simultaneously reduces index sizes, build times, and search times, so it's a win-win.

**Comment by joeytakeda** [comment]
I agree that losing the uppercase index seems like a good idea and I follow your logic here, but I'm not sure how phrasal searches could be both punctuation sensitive and allow wildcards in a way that makes sense. How should we handle instances where someone is legitimately looking for something with a question mark, for instance?

I'm also not unclear as to how the name preferentiality should be working since the XSLT doesn't increase the weight of names in any way. If the XSLT encounters a word that's a capital and not in the dictionary, then it adds that to the uppercase index as well. But when someone looks up an uppercase word (`Langdon`), staticSearch looks for both `Langdon` and `langdon`, which means that it's just doing precisely the same thing as the XSLT but with no special treatment. For instance, I see no difference in the results when searching for `Adams` versus `adams` in Despatches:

https://bcgenesis.uvic.ca/search.html?q=Adams
https://bcgenesis.uvic.ca/search.html?q=adams

Same in the WEA:

https://winnifredeatonarchive.org/search.html?q=bigelow
https://winnifredeatonarchive.org/search.html?q=Bigelow

https://winnifredeatonarchive.org/search.html?q=August
https://winnifredeatonarchive.org/search.html?q=august

So my thoughts on case sensitivity are:

* Unless we can find an instance where the capFirst does make a difference, I think we should abandon it, in part because I don't think it has ever made a difference and in part because it's difficult to know when something is a name absent of any context (of course, people can set the weight of  tagged names to 10 or whatever to make sure the names come first, if they care about that). So, in other words, MAY, MUST NOT, and MUST contain searches should all be case insensitive (which is no actual change in behaviour, as far as I can tell)
* Exact phrase search should probably be case sensitive, since it is reasonable for people to want to search for something with case sensitivity (i.e. `"August`" the month and not `"august"` the adjective). 

As I said above, I'm not sure how we'd handle both punctuation sensitivity and allowing wildcards. Any character class behaviour we have right now is accidental, I think, since wildcard characters (i.e. `*?[]`) are neither escaped nor expanded to the regex equivalence in phrasals, since that expansion happens iff the term is not phrasal:

https://github.com/projectEndings/staticSearch/blob/2510370b43a33333339a6134dde14e23fb2d276e/js/ssSearch.js#L790-L823

so wildcards technically don't work  (i.e. `*` meaning 0 or more characters) but regular expressions do, since anything in quotation marks is not escaped and thus technically interpreted as a regex. Some examples from WEA (which is running 0.9):

"year \d\d\d\d": https://winnifredeatonarchive.org/search.html?q=%22year%20%5Cd%5Cd%5Cd%5Cd%22 

And a search for "year [a-zA-Z0-9]*" yields 52 documents:

https://winnifredeatonarchive.org/search.html?q=%22year%20%5Ba-zA-Z0-9%20%5D*%22

And the behaviour seems to be the same in Keats:

http://johnkeats.uvic.ca/search.html?q=%22May%201%5Cd*%22

But since all non-wildcard punctuation is stripped out, standard regular expression characters (like `.` for instance) are stripped out (most of the time):

`"May .*"` is normalized as `"May *"`: http://johnkeats.uvic.ca/search.html?q=%22May%20+%22
But the period in `"May 1.+"` is retained: http://johnkeats.uvic.ca/search.html?q=%22May%201.+%22

So that needs to be resolved in some way, too. I think the best way forward is simply to allow punctuation in the exact phrase, not allow the wildcards or regular expressions, and escaping everything as needed.

**Comment by martindholmes** [comment]
We definitely shouldn't be stripping punctuation out of phrasal searches; that's probably simply a holdover from before we had phrasal searches at all, since it's done on the whole search string.

Is this a fair summary of what we want?

 - Phrasal searches should retain punctuation
 - Phrasal searches should have all wildcard or regex characters escaped (so no support for regex or wildcards from the user's point of view, although we will intervene to character-class the two apostrophe forms)
 - Phrasal searches should be case-sensitive, so that you can use them to search for proper names
 - A phrasal search may consist of only one word, and that's the way to search for a proper noun or a name

**Comment by joeytakeda** [comment]
Yes, that sounds exactly right. 

The only question that remains is about curly quotation marks: should we normalize curly quotation marks to straight or should we treat them as distinct punctuation characters--i.e. should `“curly”` be translated to `"curly"` (and thus an exact phrase) or as `curly` (where the curly quotation marks are simply another punctuation character to strip)?

**Comment by joeytakeda** [comment]
I've had a crack at this now in the iss98-phrasal-punctuation branch (which I had been working on before, so I added the case sensitivity stuff to it), which you can see here:

https://github.com/projectEndings/staticSearch/commit/bfcbb8d1f58563c09b224b87862effff29dceaa8

Main changes here are:

* I added `charsToDiscardPattern` to the staticSearch object, which is a regular expression for that contains all discardable punctuation characters. We use it in two places, so I thought it might as well be put up there:

https://github.com/projectEndings/staticSearch/blob/bfcbb8d1f58563c09b224b87862effff29dceaa8/js/ssSearch.js#L329

But I now realize that it doesn't include the wildcard characters, which it should if wildcards are disallowed. I'll fix that.

* Rather than normalizing the punctuation in one shot at the beginning, that normalization happens during the character-by-character iteration for creating the string to search: if `inPhrasal` is true, then the punctuation is copied over; otherwise, the punctuation is simply skipped and not added to the string:

https://github.com/projectEndings/staticSearch/blob/bfcbb8d1f58563c09b224b87862effff29dceaa8/js/ssSearch.js#L711-L732

* The query box value is replaced after all of the terms have been normalized by taking all of the terms (before they're sorted) and joining them with spaces.

https://github.com/projectEndings/staticSearch/blob/bfcbb8d1f58563c09b224b87862effff29dceaa8/js/ssSearch.js#L737-L744

* The phrasal is no longer case insensitive and any Regex-like characters are escaped

https://github.com/projectEndings/staticSearch/blob/bfcbb8d1f58563c09b224b87862effff29dceaa8/js/ssSearch.js#L1511-L1516

**Comment by martindholmes** [comment]
Hmm. Straight double quotes are the delimiters for phrasal searches; if you then put curly quotes inside them, presumably you're searching for curly quotes, or at least you're searching for quotes without knowing whether they're curly or not. On the analogy with apostrophes, then, we should character-class them when we're doing the actually phrasal search. Or is that just going too far? When you're doing a phrasal search, are you ever likely to make one that spans quotation boundaries? Maybe with so-calleds.

**Comment by martindholmes** [comment]
OK, let's load this branch up into our test projects and see what happens. I'll go for Keats, MoEML and Graves.

**Comment by joeytakeda** [comment]
Sounds good! I've just fixed a small bug in the input string replacement (it wasn't adding '+' for MUST_CONTAIN nor '-' for MUST_NOT_CONTAIN so I've added those) and made the wildcard regex more expansive in cases where wildcards aren't enabled. Do we know of any projects that don't have wildcards enabled?

**Comment by joeytakeda** [comment]
> Or is that just going too far? When you're doing a phrasal search, are you ever likely to make one that spans quotation boundaries? Maybe with so-calleds.

Must of the time, those quotation marks--especially curly ones-- will be created by CSS anyway, so they won't actually be in the document and thus unsearchable. But I don't think there's really any harm in retaining them and then character classing them, so we should probably just do that for consistency's sake.

**Comment by martindholmes** [comment]
I have wildcards enabled in all my projects.

**Comment by martindholmes** [comment]
I've killed and restarted those three builds to catch up with the changes. Graves and Keats will be done in fifteen minutes or so.

**Comment by martindholmes** [comment]
Looks good in Graves.

**Comment by martindholmes** [comment]
Also looks good in Keats, and the apostrophe character class is working. We now need to cut out the calls to the upper-case index, which are still happening. @joeytakeda do you want to go ahead with that? More familiarity with the JS will be good.

**Comment by joeytakeda** [comment]
Sure, can do. I’ll just do it in the same branch, if that’s alright, since it’ll be easier for testing. 

Should we retain the directory structure of `searchDir/lower/token.json` or should we just ditch it too and do `searchDir/token.json`? I can’t think of a reason not to ditch it, can you?

**Comment by martindholmes** [comment]
I agree, let's ditch it.

**Comment by joeytakeda** [comment]
(We have a few tickets on the related issues, but I'm just going to comment on this one for now.)

* The uppercase index should now be removed. I realized that we couldn't ditch the subdirectory, since it would mix the JSON files up with the report, stopwords, etc, which wasn't fun to work with, so I've just changed the directory to `theSearchDir/stems/`. 
* Removing the uppercase index also means that we no longer need the dictionary in the tokenization process, which simplifies the main code base quite a bit. Since all we're using the dictionary (and the isForeign) check for at this point is in the reporting stage, I've moved that processing to `create_reports.xsl`. This should be faster by quite a bit.
* I've removed the `startsWithCap` property across the JS since it didn't seem to be necessary.

One thing I wanted to confirm, though, is whether there are ever instances now where `@data-staticSearch-stem` is ever going to be a space-separated token? I'm almost certain that the upper/lower thing was the only reason why the staticSearch-stem was ever more than a single token; if that's the case, then our JSON processing can be made a bit more efficient too since we wouldn't have to tokenize the `@data-staticSearch-stem` when grouping. 

I'll switch both LOI and WEA over now; LOI will be the real test as to whether this has made the indexing process any faster.

**Comment by martindholmes** [comment]
I've kicked off new Keats, Graves and MoEML builds, so by tomorrow we should have good testbeds ready. I'm not sure about `@data-staticSearch-stem`; have to go through the code and think about it...

**Comment by martindholmes** [comment]
I think we have a big problem with putting the expansions from wildcards back into the search field. Put `discov*` into the Keats search field and you'll see what I mean; the user will be very confused by what happens there, and the resulting URL is too long to be a convenient bookmark. In addition, the expansion on one day will not necessarily be the same as the expansion in a later edition of the text, so bookmarking a specific expansion is going to be misleading. Contrast that with the simplicity of the same search in the live MoEML.

**Comment by joeytakeda** [comment]
Ah you're right--I didn't realize that was happening. Since we're doing the normalization in the iteration rather than at the beginning, I had to move the query box replacement after all the terms were added, but missed that the wildcards were of course expanded. I'll fix that now.

**Comment by martindholmes** [comment]
I'll kick off those three builds again when you're done, and we can hammer on them. Is WEA switched to this branch too, or is that too complicated because of the overrides?

**Comment by joeytakeda** [comment]
Should be fixed in commit b676198d59e96856549b70afd3528aefe7375b40. Rather than using `this.terms`, the cleaned up query string gets gets pushed into `this.normalizedQuery` and then joined (a bit of a simpler approach than the mapping).

**Comment by joeytakeda** [comment]
I've just tested with the WEA and LOI and most things are looking right. The wildcard replacement is now fixed (so `can*` is retained in the query string) and exact punctuation phrases are working nicely. However, two things I noticed:

* I hadn't added curly quotation marks to the discard pattern, so they were erroneously being looked for in phrasal searches. I've just put a commit that fixes that, though.
* Phrasals currently fail to work if the quoted string begins or ends with punctuation. For instance, a search for `"phrase “guard dog” confounds"` correctly returns the single match, but `"“guard dog”"` doesn't. I think this is due to the constructed RegEx, which is expecting whole words only since the regex is anchored by `\b` (line 1506):
https://github.com/projectEndings/staticSearch/blob/92f3f3451c60b0123553bf56c8c88e541b358109/js/ssSearch.js#L1502-L1506

Is this something we should handle? On the one hand, I can imagine someone wanting to be able to search for instances where a word ends a sentence (i.e. `"John?"` versus `"John"`); on the other, it really seems like an edge-case.

If we don't want to handle leading/trailing punctuation, then we should just trim it from the phrase (so that `"John?"` becomes `"John"`) and search for that. If we do think it's worthwhile, then we'll have to rethink how the regex matching is happening in the phrasal search. One option there is only use the word boundary anchor on the ends of the phrase that begin or end with a word character, but there'll need to be some testing there to see how well that would work/what sort of matches we might get.

What do you think?

**Comment by martindholmes** [comment]
Maybe we should just discard the word boundary terminators altogether? Then you could search on an imperfectly-remembered  phrase: `John discover` to find `John discovers` or `John discovered`?

**Comment by joeytakeda** [comment]
Yes, I think that's a good idea, especially since one could simply add a space at the end (for languages like English) to do an exact search for a word. I'll do that now.

**Comment by joeytakeda** [comment]
Trying this out now and it breaks the test set, since `"dog"` finds another hit in with `dogs`. And I'm not sure if that's really what we want, because it removes the ability to easily find all of the instances of a single word (i.e. I want to see all instances of singular `"dog"`, including instances when it is trailed by a comma or surrounded by brackets, but not in `dogged`).

So I think only using word boundaries if the thing doesn't itself start or end with a word-boundary like thing is the right approach, since that maintains the existing behaviour (which I think is right) but also allows for punctuation.

**Comment by joeytakeda** [comment]
I've gone ahead and just added the start/end boundary switch, but we can change that if we want. In doing so, I've also turned the regex creation process into its own function (`staticSearch~phraseToRegex`): it's a tiny function with only a few operations, but it is conceivable that someone would want to modify just that (and not the entire `processResults` function). Plus, it's a similar operation to the `wildcardsToRegex` function, so it's a bit better parallelism.

I've also added three new tests to test beginning, middle, and end punctuation in phrasals.

**Comment by martindholmes** [comment]
Thanks for all this excellent work! I think you've completely got the hang of the JS at this point, so if either of us dies the other one can keep the project moving. :-) I just added a semi-colon to the end of a line. Good to have the new tests, too; that was next on my list. Pull request time?

**Comment by joeytakeda** [comment]
Great--will do a PR now.

**Comment by martindholmes** [comment]
Any reason not to close this now?

**Comment by joeytakeda** [comment]
The projects have been switched to dev and seem to work well, so I'll close this now.

**Comment by joeytakeda** [comment]
Posting this here for future reference, since I found this ticket while I was trying to remember why we had decided to make phrasal searching case sensitive (which, after reading this thread, is a decision I still agree with). However, in the Lyon in Mourning project, we are often trying to search for exact phrases in titles, but since titles have odd capitalization, it was near impossible to get any results (i.e. my Dwelling house vs. My Dwelling House vs. my dwelling House etc) 

We already have some slight extensions to staticSearch, so it was easy to override the case sensitivity in phrasal searching—posting the snippet here in case in case it's useful for others:

```
    /**
     * @description Overrides the phrase to regex method to allow for case-insensitive phrasal
     * searching
     * @param str {string} The phrasal string to process
     * @augments external:"StaticSearch".phraseToRegex
     */
    phraseToRegex(str){
       try{
           let re = StaticSearch.prototype.phraseToRegex(str);
           let source = re.source;
           return new RegExp(source, 'i');
       } catch(e){
           console.log('ERROR: Cannot construct new regex from ' + str);
       }
    }
```

**Comment by martindholmes** [comment]
+dwelling +house would find it, no? Especially if you're doing "Search only in" titles.

**Comment by martindholmes** [comment]
But of course we could make this configurable. Do you want to do that?

**Comment by joeytakeda** [comment]
I suppose we could make it configurable, but I'm hesitant to add more configuration options to the config. As far as I know, case sensitivity hasn't been an issue for any of the other projects, so I'm happy to just override the method for now unless it becomes clear that more projects want case insensitive phrasal searches

**Comment by martindholmes** [comment]
Agreed. We do have a lot of config options. :-)
