### ISSUE TITLE
contextImages feature, and/or more generic extension mechanism

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#110]
This arises out of an email discussion, summarized here:

The initial requirement, for the Mariage project, was a mechanism for associating an image with each KWIC result, in addition to (or instead of) a single image for the whole document. The mechanism proposed is:

 - The user adds `@data-ssContextImage` attributes at any appropriate level in their documents.
 - The tokenizer tracks the nearest ancestor instance of such an image (using xsl:accumulator?) and adds it as a value to the JSON for each kwic.
 - The JS notices the existence of this property and outputs img elements into the search results as appropriate.

We then proceeded to consider a more generic extension mechanism whereby you may place any attribute whose name matches `/^data-ss[A-Z]/` and the tokenizer will output those values as appropriate into an array for each KWIC in the JSON. We would then provide an extension mechanism so users can write custom handlers for these things for their own sites.

The extension mechanism option might be very useful, but only for people who can write JavaScript (which might be a minority of our users). It's also not clear how the extension mechanism could/should be hacked into the JS. It's easy enough to override an existing object method on the prototype, and write your own version based on the original method, so perhaps we don't need anything specific at all there; if you can write JS, you can do this anyway.

**Comment by joeytakeda** [comment]
The reason I like the extension mechanism is that this allows people to add metadata to the tokens without needing to modify the XSLT; on balance, I think more people will know JS than XSLT. I also think that any custom attributes should be added to the output KWIC item since that provides an even easier way for people to do stuff with the object--they could do stuff in CSS or they can use the pre-existing search finished hook (or they could simply customize the resultsAsHtml method as you said).

Main issue, though, is naming collisions: we already have a few data-ss* things, so custom properties would probably need to be differentiated in some way: maybe `@data-ssCustom*`. That way, if someone creates a `@data-ssCustomLabel` and we go ahead and make a `@data-ssLabel`,  any updates wouldn't bork their existing configuration. (There's also a benefit, I imagine, for development: you add a custom thing, file an issue about it, it gets implemented, and then you can just change all of your `@data-ssCustom` to `@data-ss`). 

(In terms of the tokenizer accumulating properties: right now, we can't use accumulators since we're iterating rather than pushing through templates: that said, I think we should migrate a portion of the JSON processing to templates, but that's a broader change and probably its own ticket.)

**Comment by joeytakeda** [comment]
Er, scratch that last point--accumulators seem to work even if you're not using templates: https://xsltfiddle.liberty-development.net/6q1SDkA/2 (testing in oXygen as well and also works)

So we don't even need to move to a templating system for the accumulators to work: we should be doing this for weights and contexts regardless of what happens in terms of contextImages or the generic extension mechanism.

**Comment by martindholmes** [comment]
Good news about the accumulators; in my mind also they were push rather than pull things, but when you think about it, most transformations are neither purely one thing nor the other, so they would have to work more generally.

I hadn't really understood the idea of pushing out the attributes onto the KWICs automatically in the HTML rendering. That really makes sense. We could have some built-in CSS for a specific `@data-ss-c-img` attribute that uses the before pseudo-element to render the image (although we'll have to see how fast that is in comparison with adding an img element at render time).

To keep the size of index files down, we should use short property names if we can, though. I know JSON gets zipped, but if we go for something like:

prop: [
   {cImg: 'theImage.png'}
]

for the context-image, that'll keep the size down. We could make it `@data-ss-c-img` and document it. Then we can add automated support for any other `@data-ss-custom*` attributes, where we put them into the JSON without the 'data-ss-custom' bit, but restore it when we add them to the KWIC output. (I'd say keep the "custom" bit so users know they're in control of those atts.) I also think we should lower-case these things and use dashes; auto-conversion to camelCase for JS access is (I think) supported everywhere.

**Comment by joeytakeda** [comment]
My original thinking for the `-custom` bit was to separate stuff staticSearch handles versus stuff staticSearch doesn't handle: i.e. this image feature would have handling and documentation, so it would be `@data-ss-img`.

But after reflecting on it, that seems a bit over engineered. We should just keep it simple with `@data-ss-*`: anything with a `@data-ss-*` gets placed in the JSON; most of the time we know what those properties mean, but because we'll just check for any `@data-ss-*` stuff, anything you put there will also travel with the token. There is a chance that there'd be a naming collisions, but the likelihood of that happening—someone customizing staticSearch and keeping up with all of the updates and we so happen to create another property with the exact same name—is so minimal that it's not worth making special accommodations for it, I think. Plus there's nothing stopping people from prefixing the values themselves if they want to be certain they won't collide.

So here's how I understand it:

```html
<div data-ss-img="my/image.png" data-ss-date="1919" data-ss-label="Something" data-ss-my-thing="Foo">
<p>foo</p>
</div>
```
Then when the XSLT creates `foo.json`, there'll be a `prop` bit:

```json
prop: [
{"img": "my/image.png"}
 {"date": "1919"},
{"label": "Something"},
{"myThing": "Foo"},
]
```
(Any reason why this needs to be an array of objects rather than a single object?)

And then when the JS creates the `<li>` for the KWIC, it will create this HTML:

```html
<li data-ss-img="my/image.png" data-ss-date="1919" data-ss-label="Something" data-ss-my-thing="Foo">Hello</li>
```

Does that sound right to you?

In terms of the image thing, I think adding the `<img>` is probably the safest bet: the CSS would be nice, but images in CSS can be a bit buggy (especially in Safari) plus they're invisible to screen-readers. (But adding the `@data-ss-img` will mean that styling them slightly differently than a regular bit `<li>` will be much simpler).

**Comment by martindholmes** [comment]
I'm fine with a single JS object there.

I'm presuming the JSON will insert each of those atts as properties in the context object, right?

I think the screen-reader thing is a red herring, because in order to make an img meaningful to a screen-reader, you have to give it an alt attribute; the text for that attribute would have to come from somewhere. I didn't know Safari had problems with simple images for content properties; that's alarming if it's so. Let's try the CSS approach first, at least.

**Comment by joeytakeda** [comment]
Sounds good. I'll start a new branch for this now where I'll  also be refactor the code slightly to use accumulators.

**Comment by joeytakeda** [comment]
I think I have branch 110-data-extension working now. I've added `@data-ss-stanza` and `@data-ss-line` to the poems/ditty.html and all tests still pass. The JSONs seem to have the prop content in their `prop` map, but I haven't touched the Javascript to do anything with them. I've now switched branches for WEA and LOI and all seems to be well.

Everything that could be has also been converted to accumulators and I've split out the context creation into its own template just to make testing a bit easier. I've also added some better output for the JSONs in non-verbose mode (spitting out a message at every ~10%).

**Comment by martindholmes** [comment]
Thanks! I'll do the JavaScript asap, and I'll also add some fragment images to the test set.

**Comment by joeytakeda** [comment]
That sounds good to me! I’ll continue working on the XSLT sometime today, but it shouldn’t matter for the JS so we shouldn’t run into any conflicts.

**Comment by joeytakeda** [comment]
Commit https://github.com/projectEndings/staticSearch/commit/a826e31210378bd9cc249c2f198562329c52421a is an attempt to solve the memory issues. 

First, I added an extra step to the enumeration pass in tokenize to remove superfluous `@data-staticSearch-context` declarations; since we have already tagged all of the spans, we can remove any context declarations that don't need to be there. I.e.: rather than

```
<body data-staticSearch-context="true">
    <div data-staticSearch-context="true">
        <div data-staticSearch-context="true">
            <p data-staticSearch-context="true">In <span data-staticSearch-pos="33" data-staticSearch-fid="text" data-staticSearch-stem="english">English</span> <span data-staticSearch-pos="34" data-staticSearch-fid="text" data-staticSearch-stem="orthographi">orthography</span>[...]</p>
        </div>
    </div>
</body>
```

We get this:

```
<body>
    <div>
        <div>
            <p data-staticSearch-context="true">In <span data-staticSearch-pos="33" data-staticSearch-fid="text" data-staticSearch-stem="english">English</span> <span data-staticSearch-pos="34" data-staticSearch-fid="text" data-staticSearch-stem="orthographi">orthography</span>[...]</p>
        </div>
    </div>
</body>
```

I did that since if we do end up using accumulators for contexts, then this would mean there are far fewer things to accumulate; but I've also now switched the context checking from an accumulator to an ancestor axis. If the LOI build passes, then I'll add the accumulator back in to see if it breaks it.

**Comment by joeytakeda** [comment]
@martindholmes I started to ask this question over email, but realized that there are a few other things to think about and that it's probably worth outlining here as documentation:

What I've done so far is:

* All data-ss-* are treated as strings in the output map
* Hyphenated strings after `@data-ss-` are converted to camel case
* Properties are inherited and they override each other
* Only output the properties that are inherited by that specific instance of that token
* Create the property map iff there is some property set for that token

So to give an example: some HTML like this:

```
<body>
    <div data-ss-img="my/image.png" data-ss-label="Div 1">
        <p data-ss-para-num="1">Hello</p>
        <div data-ss-img="my/otherImage.png">World</div>
    </div>
    <div>
        <p>Foo</p>
    </div>
</body>
```

would produce the following JSONs (truncated for brevity here):

hello.json: 

```
{
"weight": 1,
"form" "Hello",
"context": "<mark>Hello</mark>"
"prop": {
      "img": "my/image.png",
      "paraNum": "1",
      "label": "Div 1"
     }
}
```

world.json

```
{
"weight": 1,
"form": "World",
"context": "<mark>World</mark>"
"prop": {
         "img": "my/otherImage.png"
         "label": "Div 1"
      }
}
```

foo.json

```
{
"weight": 1,
"form": "Foo",
"context": "<mark>Foo</mark>"
}
```

Does this structure seem right to you?

**Comment by martindholmes** [comment]
@joeytakeda Don't do the camel-case thing; I don't see any value in it. The JS isn't reading those things from attribute names, it's writing them to attribute names, so there's no need to transform them at all. The JS is already doing this (in my last commit). So I'd rather see:

~~~~~
{
"weight": 1,
"form": "Hello",
"context": "<mark>Hello</mark>",
"prop": {
      "img": "my/image.png",
      "para-num": "1",
      "label": "Div 1"
     }
}
~~~~~

Otherwise this looks perfect.

**Comment by joeytakeda** [comment]
Perfect--just sent down a commit that removes camel casing. And the LOI build passed and a quick test looks like everything is still working correctly (it shaved about 15 minutes off of the build, too).

**Comment by martindholmes** [comment]
My only problem now is getting that `content: url(attr(data-ss-img))` to work. Firefox tells me it's an invalid property value. :-( See anything wrong?

**Comment by martindholmes** [comment]
Ha, can't be done [yet]: https://developer.mozilla.org/en-US/docs/Web/CSS/attr(). Oh well. So I guess I'm going to special-case the data-ss-img property to insert an actual image, unless you can think of any other approach.

**Comment by joeytakeda** [comment]
Ah right--I thought I had done that before, but now I recall that I've always done that by setting custom properties on the item:
 
```
<div style="--img: url('path/to/my/image.png')">
```

But that would still be a special case thing and quite hacky, so I'd say inserting the image literally is good--one advantage is that the `<img>` could be wrapped as a link to the fragment if desired.

**Comment by martindholmes** [comment]
OK, I've added that special handling; I've switched Mariage to use this branch, and I'll start a Mariage build to see what comes out. There'll be some styling to do; we'll have to decide how much to constrain these images by default, and how much to leave it up to the end user.

**Comment by martindholmes** [comment]
It's working in Mariage; I've just committed new CSS overrides to Mariage to constrain the size of the images, since they're huge, so when that's gone through the build process we'll have a working demo. The test dataset also now has an example you can test by searching for "elephant".

**Comment by joeytakeda** [comment]
Thanks for putting in that example (great image choice!)

In terms of the default styling, I was thinking that the image should be a block above the text of the KWIC with a max-width of 100% (so that it's responsive and can also take up the whole width if it needs to) and each item should have a bit of a margin to separate the kwics with `data-ss-img`. 

```
#ssResults li[data-ss-img]{
 margin-top:1em;
}

#ssResults li[data-ss-img] > img{
    display: block;
    max-width: 100%;
}
```
![Screen Shot 2021-01-16 at 7 28 14 PM](https://user-images.githubusercontent.com/17664763/104830314-8bae5800-5832-11eb-8479-3293f711dc4e.png)

I've just added it the local `<style>` in test/search.html so you can see how it looks; I think it cleans it up a little and makes the relationship between the img and the KWIC clear without adding too many additional styles that people will override anyway.

**Comment by martindholmes** [comment]
I've been playing around with the styling on Mariage, and I think I prefer a system where the image is to the left of the text, while the text wraps alongside it. I think perhaps the way to do this is to make the li into display: table-row, and the children into table-cells with vertical-align: middle. It's not ideal for horizontally-long images, but for others it's good. I haven't actually implemented that solution in Mariage yet, though; right now it's just putting them next to each other. I'll send you a link offline.

**Comment by martindholmes** [comment]
After a bit more experimentation, I think:

 - The KWIC itself should be wrapped in a span, so it can be styled as a segment separately from the image when there is one.
 - `li[data-ss-img]` should be `display: table-row`.
 - `li[data-ss-img]>*` should be `display: table-cell; vertical-align: middle`.
 - `div#ssResultSet>ul>li:nth-child(2n)` should be `background-color: lightgray; padding: 0.25em`.
 - `div#ssResultSet>ul>li>div>a` should be `font-size: 120%`.

That gives us clear separation between result sets from individual documents; a more distinct and visible document title; and a decent layout for KWICS and their associated fragment images. Any objections to my trying that out in this branch?

**Comment by joeytakeda** [comment]
> * The KWIC itself should be wrapped in a span, so it can be styled as a segment separately from the image when there is one.

Agreed.

> * `li[data-ss-img]` should be `display: table-row`.
> * `li[data-ss-img]>*` should be `display: table-cell; vertical-align: middle`.

Why not just use flex? We use flex throughout our default CSS anyway and it would cut down the number of rules:

```
#ssResults li[data-ss-img]{
display:flex;
align-items: center;
}
```
(I've also scoped this to `#ssResults` since someone could have a `<li data-ss-img="my/image.png">` in their actual HTML to generate that result.)

What about the `<img>` sizing? In the Mariage sample, the imgs have a set max-width and max-height; I would assume we'd set those, too?

> * `div#ssResultSet>ul>li:nth-child(2n)` should be `background-color: lightgray; padding: 0.25em`.
> * `div#ssResultSet>ul>li>div>a` should be `font-size: 120%`.
> 
> That gives us clear separation between result sets from individual documents; a more distinct and visible document title; and a decent layout for KWICS and their associated fragment images. Any objections to my trying that out in this branch?

That seems fine to me; I override the majority of the styles anyway, so I'm not the best arbiter of what's most useful in terms of the default styles. We should note that we've added these styles in the release notes, though, since they will affect everyone.

**Comment by martindholmes** [comment]
I was thinking that with table-row and table-cell we might get the components to line up in columns, which would be a good thing, but I think that would need `display: table` on the `ul`, and of course sometimes you won't have an image, so perhaps flex is better. Presumably we'd have `flex-wrap: nowrap` to keep things in line.

**Comment by martindholmes** [comment]
The JS now wraps the kwic in a span, which is making it much easier to do layout in Mariage. When I'm happy with how that looks, we can figure out what elements of it should be moved back into the default staticSearch CSS.

**Comment by martindholmes** [comment]
@joeytakeda I've added documentation for these custom extension attributes, including the data-ss-img which has built-in handling. Can you think of anything left to do, or are we ready for a merge?

**Comment by joeytakeda** [comment]
Documentation looks good to me -- thanks for adding that! Just did a quick rebuild of the test page and looks good, so I think we're ready to merge.

Once that's merged in, I'll switch WEA and LOI back to `dev` and see what kind of overrides (if any) are necessary in terms of keeping the style consistent for those projects.

**Comment by martindholmes** [comment]
I've merged, and switched Mariage over to dev. Once we know all is well, we can delete that branch.

**Comment by martindholmes** [comment]
Everything looks good at this point. Closing.
