### ISSUE TITLE
When building a French search page, button captions should be French

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#143]
The JavaScript is able to read the root html element's lang attribute and use French captions, but the XSLT that builds the page isn't yet doing that, so the buttons (Search, Clear etc.) appear in English.

**Comment by martindholmes** [comment]
@joeytakeda There are two ways to attack this: one is to store French captions in the XSLT source and use them when required, and the other is to include those captions as part of the caption set of the JavaScript, and have the JS object replace the captions when it initializes. I think I favour the former because there won't be a visible English caption that gets switched as you watch. (I'd also like to avoid adding more work into the JS object constructor, which is getting pretty long.) What do you think?

**Comment by joeytakeda** [comment]
I like the idea of putting them in the XSLT rather than the JS as well.

But I'm not sure what the best way to handle it in XSLT will be: should we simply check the root lang and switch the captions automatically? That would work, of course, but then that's only a solution for French.

The other option is that we have some sort of mechanism for supplying captions to the XSLT. That would be nice to have, of course, but I can't think of a way to do it without adding a pile of complexity on to our already complex configuration system.

**Comment by martindholmes** [comment]
I think since we have two French projects now (Francotoile is fully-staticized and in testing mode) and we have a French stemmer, it's OK to special-case French. We do need a broader strategy for internationalization, but that needs some discussion. In the meantime, we can have a captions.xsl file with the two sets of captions in it.

**Comment by joeytakeda** [comment]
I've just added caption handling in a branch. I've created a set of captions and an associated function to check whether or not that caption exists for a given language.

**Comment by martindholmes** [comment]
Great! "Clear" is "Effacer"; for "Powered by" let's go for "Réalisé par", and for "Searching..." how about "En cours...". We can get those checked later.

**Comment by martindholmes** [comment]
Add those before I pull?

**Comment by joeytakeda** [comment]
Thanks! French captions now added.

**Comment by martindholmes** [comment]
Now merged, and I've kicked off a Mariage build to see what happens. :-)

**Comment by martindholmes** [comment]
Looking good -- we have French captions in Mariage. I think we can close this now.
