### ISSUE TITLE
We should test the Google Closure compiler

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#146]
The JS is getting large enough to be worth minifying for production use -- I'm noticing a split-second of delay when search pages load -- and I'd also like to be able to split it out into smaller modules for easier development, but still deliver a single file at build time. The Google Closure compiler is open-source Java, so it would fit into our ecosystem, but I'm not sure about the status of ES6 support, so we'll need to do some testing. If it doesn't work, at the very least we can write our own simple comment-stripping whitespace-normalizing thing in XSLT.

**Comment by martindholmes** [comment]
Tested this morning: the size reduction is about 33%, and the speed increase is noticeable even in the tests. Also, the compiler found two minor issues (unreachable code, which was actually a duplicated block) and a duplicate assignment to an object property. I think this is a definite go.

So next we should figure out what sort of reorganization we want to do. We could split each of the objects out into its own file, including the upcoming typeahead object that we're working on now; that would give us four distinct files. We could then combine those into a single file at build time, then call the compiler on that file. We could then keep the original file as ssSearch_debug.js and provide that to the project as well, so that if any debugging is necessary they can just switch to that file and provide us with more useful reports, but the ssSearch.js that's linked is actually the compressed one.

Other things to think about: 
1. Do we put the compiler in our repo? I think yes, because pulling it on every build is a nuisance, and it may change its behaviour at some point and break things. We can update it periodically following testing, as we do with Saxon.
2. What do we want to provide in terms of a license in the JS? All the comments get stripped automatically, but there are options for providing license info that's retained by the compiler.
3. Should our test build have a switch that allows us to alternate between the compiled and the uncompiled versions? If so, which should be the default?

**Comment by martindholmes** [comment]
Working on this in branch issue-146-closure.

**Comment by joeytakeda** [comment]
> We could split each of the objects out into its own file, including the upcoming typeahead object that we're working on now; that would give us four distinct files. We could then combine those into a single file at build time, then call the compiler on that file. 

Unless I'm miscounting, I think it would be three, not four, since we'd want ssFinder to remain separate--it doesn't need all the rest of the staticSearch stuff, so I don't think that should be built into the minified dist file.

> We could then keep the original file as ssSearch_debug.js and provide that to the project as well, so that if any debugging is necessary they can just switch to that file and provide us with more useful reports, but the ssSearch.js that's linked is actually the compressed one.

From what I can tell, the closure compiler can do the concatenation too, right? So we could just call the closure compiler to concatenate the file, and then call it again on the concatenated file to do the whitespace/comment stripping etc. 

I'd be inclined to say we should have ssSearch.js as the concatenated file and have a ssSearch.min.js as the minified one, since that's by far the most common naming practice. We expect people to be using the file as encoded by the build process, so we can switch the XSLT to use .min.js rather than .js; and in the cases where someone has hardcoded a reference to ssSearch.js, there won't be any change in behaviour (they just won't get the minified file).

> * Do we put the compiler in our repo? I think yes, because pulling it on every build is a nuisance, and it may change its behaviour at some point and break things. We can update it periodically following testing, as we do with Saxon.

That sounds fine to me.

> * What's our naming convention for the modular files? There are various standard approaches...

I would be inclined to just call them by the name of their class, so StaticSearch.js, SSTypeahead.js, SSResultSet.js. 
 
> * What do we want to provide in terms of a license in the JS? All the comments get stripped automatically, but there are options for providing license info that's retained by the compiler.

From what I can tell from the JS file, our current license is basically MIT--do whatever you want with it.  I like MIT and I particularly like how short it is (so it's much nicer to put in the output JS); if we wanted to have Mozilla license for the JS, too, then I'd say we should just put a pointer to the LICENSE file in the repo.

> * Should our test build have a switch that allows us to alternate between the compiled and the uncompiled versions? If so, which should be the default?

We should probably test all of the modules, the concatenated version, and the minified version for completeness' sake. So one option is to have a process after the search page creation that triplicates the test page so that all of the same tests are run across the three combinations:

* A search page that includes all of the modules in the order they'll be concatenated to make sure all of the modules work properly
* A search page that includes the concatenated file to make sure the concatenation worked as we expected
* A search page that includes the compiled file to make sure the closure compiler worked as we expected

**Comment by martindholmes** [comment]
We'd have StaticSearch, SSResultSet, XSet, and TypeAhead files, I think. XSet is tiny but it's a distinct class. I would do the concat first because we'd want a single debug version that people can easily switch to, then run closure on that to get the compressed version. I don't know if it's worth having the all-four-files version of the test, because it's essentially no different from the concatenated version; I'm not proposing using actual JS Modules, because I've never been able to get that to work for real in actual browsers. For license stuff, I think we probably want our own names in there somewhere too, as well as a pointer to the MIT license.

**Comment by joeytakeda** [comment]
Ah yes, XSet. Forgot about that.

The reason why I say the all four version test is to make sure nothing is to making sure our concatenation process is working properly. And wasn't suggesting modules (though, I do use modules almost exclusively these days and haven't had any issues on any browsers), but just the sequence of scripts which should have the same effect as the concatenated file. But, that said, concatenation may never cause any issues, so it might not be worth testing. But I still think that we should run all of our tests on both the full and minified for completeness' sake.

**Comment by martindholmes** [comment]
There is also actually going to be a fifth file, now I think about it; there's a pile of preamble -- constants and some stuff in the ss namespace. I'd put them in a static class if it were Java, but they could be in an ssUtilities.js file. This might be a good time to namespace the consts, though, actually.

But I think the concatenation is literally that; I would put the consts and stuff first, but in actual fact, since the meat is in classes which are only instantiated when the main StaticSearch object is instantiated, by an external call, the sequence probably makes no difference.

I agree we should test both, though, and that'll give us the opportunity to time them and find out what benefit we're getting from the compiler too.

**Comment by martindholmes** [comment]
I'm rolling the stemmer into the compilation process too, since the compiler complains if it doesn't find it because the main class creates an instance of it. The compiler generates lots of warnings, which seem to be mainly benign, but they might prompt me to revise a few things in my rather-neglected code-refactoring branch. Hope to have the issue-146-closure branch testable with projects some time today.

**Comment by martindholmes** [comment]
Pull request is ready.

**Comment by martindholmes** [comment]
Pulled -- thanks @joeytakeda. What's left is documentation, which we normally do in dev.

**Comment by joeytakeda** [comment]
Results are in for LOI and there's a noticeable speed up, which is great.

One interesting thing that I've noticed, though: it looks like the closure compiler is transpiling our ES6 code to ES5:

```
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.objectCreate=$jscomp.ASSUME_ES5
```

The documentation only mentions that transpilation for WHITESPACE_ONLY, but it looks like the same applies for simple: https://developers.google.com/closure/compiler/docs/compilation_levels#simple_optimizations

I think I'd prefer just doing ES6 --> ES6 rather than ES6--> ES5, since I'd rather not have a bunch of injected at the top (plus we'd save even more space). What do you think?

**Comment by martindholmes** [comment]
All the warnings are fixed or suppressed at this point; I think we may revisit the compilation target choice once in a while, but this issue is essentially done, so I think this can be closed.
