### ISSUE TITLE
Allow other block-level elements as containers for staticSearch

### ISSUE THREAD

**Issue by gtnewton** [projectEndings/staticSearch#153]
Right now, makeSearchPage.xsl assumes that it will be adding markup to a 'div' element with the id 'staticSearch', but it makes sense to allow for some flexibility.
I propose to allow 'div', 'fieldset', 'form', 'header', 'main', 'section', and maybe 'details' (although I think that's a bit out there). Other block-level elements are either not flexible enough to contain the kind of markup needed (like 'p'), or are semantically inappropriate (like 'address' and 'aside').

**Comment by martindholmes** [comment]
I think on balance, article, main, section, and div make a lot of sense. , but I'm not sure I agree about things like fieldset, because we're already creating a bunch of divs and fieldsets in the filter output; there's a history of browsers rendering fieldsets badly, and if they're heavily nested there might be significant issues. It makes no sense to me to put your entire set of search controls into a header. We add a form anyway, and you don't want nested forms. Of course, you can use any element and put your div with the id inside it anyway.

**Comment by gtnewton** [comment]
I agree. I was just briefly riffing on the available elements. You're right about the form stuff, of course.

**Comment by joeytakeda** [comment]
This seems like a good idea to me. Just did a brief investigation of the CSS/JS (in `dev`) and I could find no instances of `div#staticSearch` (or anything referring to `#staticSearch`), which means that the only bit of code this would change is `makeSearchPage.xsl`.

I agree with Martin's list, but I would also add `aside` and `body`.[1] `aside` since it's perfectly reasonable for someone to have a search that is "is only indirectly related to the document's main content" (there's no reason why a search can't be a sidebar, is there?) and `body` since there's nothing stopping someone from having a document whose entire contents is just the search. Of course, we'll never be able to confirm that what someone is doing is actually a good idea (i.e. `<header><div id="staticSearch"/></header>`), but at least we can help them along. 

If we do this, then we should probably make the XSLT a bit more strict and explicit:

* The XSLT should fail if there is more than one element with `id='staticSearch'` (it current warns if there isn't one)
* The XSLT should fail if the `id='staticSearch'` element is not one of the allowed elements.

I like failing rather than warning in this instance since staticSearch provides a number of messages (especially during the tokenization), which make WARNINGs easy to miss.

<hr/>

[1]: I think it's reasonable to have a `staticSearch` *in* a `<details>` but it doesn't make sense for the `details` to the be the staticSearch, given that `details` need a `summary` and the `summary` would be wiped out by the XSLT.

**Comment by martindholmes** [comment]
I don't think the build should fail if someone uses an element that's not in our list, because they may have created a custom element specifically for the search. I think we should definitely warn, though.

**Comment by joeytakeda** [comment]
Good point re: custom elements. A warning sounds good, then.

**Comment by martindholmes** [comment]
@gtnewton In the dev branch you can now use any element to wrap the staticSearch controls as long as it has the id 'staticSearch'. You'll get a warning if it's not a div, but the build will go ahead. Closing this ticket now.
