### ISSUE TITLE
Remove inline JS and CSS

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#160]
Content-Security-Policy settings are increasingly restrictive, and one thing that's discouraged is any inline JS and CSS. We should move any code that currently ends up inside the search page into linked files.

**Comment by martindholmes** [comment]
@joeytakeda The inline JS we insert into the search page at build time currently looks like this:
~~~~~
<script>
  var Sch;
  window.addEventListener('load', function(){Sch = new StaticSearch();});
</script>
~~~~~

I can't see any reason not to just add this to the end of the concatenated JS code in the main script:

~~~~~
var Sch;
window.addEventListener('load', function(){Sch = new StaticSearch();});
~~~~~

Can you?

**Comment by joeytakeda** [comment]
In LOI and WEA, I remove that script tag entirely and create a StaticSearch after running a few other processes (i.e making sure that I have fetched some additional data to supplement the results as well as opening filter accordions). That doesn’t necessarily need to happen beforehand, but this would require some rewriting on my part. But this would also mean one couldn’t extend the StaticSearch class and initialize their own StaticSearch (new CustomStaticSearch()), since the global Sch we provide and the custom one they provide would both be bound to the same set of inputs etc. 

One way we could get around that is by making the function called on load a real function, such that it could be removed by the implementer if desired by calling removeEventListener.

**Comment by martindholmes** [comment]
Could you removeEventListener before it runs? You'd have to get your own onload event to run first somehow.

But another option is to make these two lines a separate individual JS file that you could just replace or remove after build. That might make more sense.

**Comment by joeytakeda** [comment]
It’d have to be a very precise ordering such that the invocation of the event listener would have to be placed and parsed before the removal code, which would need to be performed before load. So yes, an additional little file sounds like a much better idea 🙂

**Comment by martindholmes** [comment]
Working on this in branch issue_160_noinlinejs.

**Comment by martindholmes** [comment]
Closing this, now functioning and documented.
