### ISSUE TITLE
Custom search results display

### ISSUE THREAD

**Issue by wsalesky** [projectEndings/staticSearch#163]
We are looking to customize our search results display, essentially: 
`<a href="docURI">Title</a> : document description`

Any thoughts on the best way to do this?
Thanks!

**Comment by joeytakeda** [comment]
Hi @wsalesky — thanks for the patience here. 

You can remove the keywords in contexts by turning off that part of the indexing in your configuration (i.e. by setting maxKwicsToShow and maxKwicsToRetrieve to 0). 

Adding the document description is a bit trickier since staticSearch won't have any of that information. I've done something similar in the past by setting the `searchFinishedHook()` to a function that parses the resultsDiv and fetches information in order to place a block of metadata about the item in the results div:

https://github.com/winnifredeatonarchive/wea_data/blob/19eaa8f4689fc0c14c6cfe8dd610f271a67ad637/site/js/wea_search.js#L125-L177

You can see that in action here under the More Info show/hide: https://winnifredeatonarchive.org/search.html?q=something

A more elegant solution is to override the SSResultSet.resultsAsHtml method and create the results however you'd like; that's a bit more dangerous, though, since there's a lot happening in that function.

**Comment by martindholmes** [comment]
@wsalesky Sorry, I completely missed this ticked for some reason! For an example of overriding the SSResultSet.resultsAsHtml method, see my project here:

https://scancan.net/search.htm

and specifically this JS file, which contains just the override:

https://scancan.net/js/staticSearchOverrides.js

**Comment by wsalesky** [comment]
@martindholmes @joeytakeda Thanks, I will take a look and see what I can do. Really appreciate all the work you have put into this project.
