### ISSUE TITLE
Minor bug in test build

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#165]
The test build process is supposed to take place entirely within the test folder, with temporary content stored in test/ssTest/temp. However, during the tokenize process, a set of empty HTML files corresponding to the data files is created in ssTest/temp (outside the test folder), and not deleted at the end of the process. I haven't yet figured out why that's happening, and it seems to cause no problems, but it should be fixed.

**Comment by joeytakeda** [comment]
I can confirm this is happening for me, too. I think has to do with the build file and, in particular, this bit:

```
   <xslt
      style="${ssBaseDir}/xsl/tokenize.xsl" classpath="${ssSaxon}" destdir="${ssOutputFolder}/temp"
       reloadstylesheet="true"
       force="true"
      useimplicitfileset="false">
```

The `${ssOutputFolder}` parameter is set above as such:

```
 <!--Output folder, which is forked, depending on whether or not an output folder
        is specified in the configuration file-->
  <property name="ssOutputFolder" if:set="config.params.outputFolder"
    value="${config.params.outputFolder}"/>
  <property name="ssOutputFolder" unless:set="config.params.outputFolder" value="staticSearch"/>

```

But that doesn't get resolved into anything useful by itself (i.e. for the test it just is set as ssTest and nothing else).  setting the `@destdir` to `${staticSearchDir}/temp` works, but it still creates the empty files (since the tokenization process is creating result-documents rather than outputting directly). 

We can't get rid of the `@destdir` since it's mandatory and there's no immediate harm in creating those empty files in the`${staticSearchDir}/temp` since the only files we use are the _tokenized ones, but that's a lot of pointless files when a project has 100,000 files. 

Probably the solution here is to refactor `tokenize.xsl` appropriately so that the `<xslt>` task creates the _tokenized.html file by default, but that output URI is handled by ANT and not within the XSLT. So that would mean:

* Remove the wrapping `<xsl:result-document>` from these lines:
https://github.com/projectEndings/staticSearch/blob/e7c1423bdcd64a9d8f60d550300867fe3b4bcc49/xsl/tokenize.xsl#L228-L245

* Set the `@destdir` on the <xslt> task to `${staticSearchDir}/temp` (or, better yet, make that temp directory a property) 
* Add a mapper so that each file becomes `${staticSearchDir}/temp/name_tokenized.html`

**Comment by martindholmes** [comment]
I've added a workaround for this because it was annoying me: the empty files now go into a folder called ${staticSearchDir}/empty, and that folder is deleted immediately after the xslt task is done. We can solve the problem more elegantly when we have time.

**Comment by martindholmes** [comment]
Closing this as @joeytakeda confirms a full fix is implemented.
