### ISSUE TITLE
Test suites should be merged

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#184]
We currently have two test sets, "test" and "testWorthReading". IIRC the latter was configured in order to test two things: exclusion of documents (`exclude[@type='index']`) and exclusion of filters (`exclude[@type='filter']`). I think we did this because we didn't want to have documents in the test suite which were not used at all, so we configured the second test set to be a subset of the first.

However, the presence of two test suites is confusing, and it's also problematic in that if you inadvertently leave debugging debris around from one test suite then run the other, the initial clean process will not know to clean up the original debris (it only pre-cleans any debris from its own folders), so tokenization files etc. end up getting indexed by accident.

I think it would be much simpler just to merge the testWorthReading features into the main test suite. We could add a couple of documents to the test suite that would be excluded from the main test, but set them up so that they contain things that would be found in the current tests if the documents were indexed, thus testing the index exclusion; and we could add a few instances of a couple of random meta tags which we then exclude in the test, and have the main test suite check for the absence of matching search page controls.

**Comment by joeytakeda** [comment]
This makes a lot of sense, especially since it does cause a number of problems when re-running stuff.

However, the one issue I see here is that the current test suite necessarily tests everything; part of the advantage of the testWorthReading is to make sure there's no regression if we add a new feature (e.g. I caught a bug when doing the search within stuff through testWorthReading, since it didn't include the search within mechanisms). However it is difficult to think of any way to automate checking all of the various permutations of features in a way that wouldn't be massively convoluted.

 think merging these sound right and, unless we can think of some sort of more robust testing mechanism that would be fairly straight-forward, I'd say we can just continue with our more brute-force approach to testing things (switching various projects to the branch and make sure everything still works).

**Comment by joeytakeda** [comment]
Merged—Jenkins failed since it tried to run the secondary test set. I believe I could fix that myself, but having not used Jenkins in a couple of years now, I'll leave that to @martindholmes  :-)

**Comment by martindholmes** [comment]
Should be done now. Thanks! I'll close this if Jenkins builds and the test suite works.

**Comment by martindholmes** [comment]
All working. The tests were tripping over the debris from previous builds on Jenkins too; had to wipe out the workspace to get it clean. That shouldn't be a problem again.
