### ISSUE TITLE
Automatic scroll to results should be offset a little

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#187]
This is trivial to do so this ticket is just to remind me to do it: when a search is completed, the page scrolls down to the results, but it would be less jarring if there was a scroll offset of (say) 5rem or something.

**Comment by martindholmes** [comment]
@joeytakeda I propose handling this by simply adding:

  `padding-top: 1rem;`

to the div#ssResults ruleset; it makes for a slightly less cramped display when the page scrolls down to the results. Any objections?

**Comment by joeytakeda** [comment]
What about `scroll-margin-top: 1rem`? There wouldn't be any difference in how the ssResults would look, but the scroll would stop 1rem before it hits the top of the results—would that work?

**Comment by martindholmes** [comment]
I can't get it to work. Must be missing something.

**Comment by joeytakeda** [comment]
Well, I can't get it to work either :-) It might only work in cases where you're going because of anchor (or if you have scroll snap points defined or something).

In any case, the padding thing is much more straightforward. If we were worried about the additional space the results might take up, we could do:

```
padding-top:1rem;
margin-top:-1rem;
```

Which would work the way we want it to (I actually checked this time!) without changing the visual spacing of the results div.

**Comment by martindholmes** [comment]
Let's go with that.

**Comment by martindholmes** [comment]
Closing now.
