### ISSUE TITLE
Search page components and JSON filenames need to be aligned

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#22]
This is currently a show-stopper for the current development of th JS search object's background-json-retrieval functionality, so it's a priority.

In order for the JS search object to know the names of filter JSON files that need to be retrieved, those names have to be supplied as an attribute on the search page controls. That means that the same mechanism which creates the ids "ssDesc1" at 

https://github.com/projectEndings/staticSearch/blob/c6bf2e48b0638085207d3ef40383c94a6016b4f8/xsl/json.xsl#L509

or "ssDate1" at

https://github.com/projectEndings/staticSearch/blob/c6bf2e48b0638085207d3ef40383c94a6016b4f8/xsl/json.xsl#L566

needs to be invoked in makeSearchPage.xsl to add the same identifiers in some fashion (custom data- attributes?) to the search controls themselves. This might be a bit tricky because entirely different mechanisms are being used to handle the filters, and there's no guarantee they'll be processed in the same order in both cases. Therefore I think we need to return to the notion of generating an identifier from the filter name, by some reliable mechanism. Whatever we use only needs to work in XSLT; we don't need to do the same operation in JS, because the filter ids will be embedded in the search page HTML.

I thought about simply counting up each type of filter and assuming that if there are two desc filters I need to retrieve ssDesc1 and ssDesc2, but that won't work because the JS can't know which of those files applies to which filter, so it can't tell whether it needs to prioritize a specific retrieval or not when a filter has been used in a search request.

**Comment by joeytakeda** [comment]
Why not just assign a name to the filter at the start of the whole process? I.e. during the stemming bit, we gather up a list of all the unique filter names and assign them some id (something as simple as ssDesc1 or whatever) and add it as a data-attribute to the `<meta>` itself:

```
<meta name="Document Type" data-ss-id="ssDesc1"/>
```

That way, the JSON XSLT and the Search page XSLT can use the `@data-ss-id` when they create their respective outputs.

**Comment by martindholmes** [comment]
We can't be changing users' HTML files, though. We may not even be able to; they could be pointing the tokenizer at a read-only resource. The only one we get to change is the search page itself.

**Comment by joeytakeda** [comment]
We're not changing the HTML pages anymore than we already are. We add
`<span>`s and give each HTML page a `@data-staticSearch-id` in the
tokenization step. All I'm suggesting is that, during the tokenization
step, we assign an id to the meta tag from the outset that we can then rely
on throughout the JSON and the Search page creation processes.

**Comment by martindholmes** [comment]
I didn't realize we were actually changing the content pages during tokenization; I thought that was just an interim temp file to enable the tokenization. Do we need to change the actual pages? What happens if the files are read-only?

**Comment by joeytakeda** [comment]
I think we’re talking at slightly cross purposes :-). 

My idea is that, when we create the temporary file_tokenized in the temp directory, we assign a (somewhat arbitrary) id to each of the filters—so “Document Type” gets “ssDesc1” etc. Since we use the tokenized files for creating the JSONs and the search page, we can use that filter id as the JSON file name and we can use it in the search page HTML as a data attribute. The source HTML file itself remains unchanged, but the meta ID is consistent between the JSON creation and the search page creation.

**Comment by martindholmes** [comment]
I have added a function library with one function for generating an identifier from a label and prefix; if you're able to get the other system working quickly, we don't need that, but if you're a bit busy on other stuff I'm going to plug that in just so I can get moving with the JSON retrieval stuff. I suspect the process you've outlined above might be a little more complicated than it seems, because of the slightly unpredictable order in which for-each-group processing happens for the two processes.

**Comment by joeytakeda** [comment]
This should now be fixed. The relevant changes are in tokenize.xsl:

This bit maps the filter name to a distinct id:

https://github.com/projectEndings/staticSearch/blob/f4622196b02696defad17bca6c71d132c2d26ad1/xsl/tokenize.xsl#L52-L76

And this bit assigns the id to the meta tag:

https://github.com/projectEndings/staticSearch/blob/f4622196b02696defad17bca6c71d132c2d26ad1/xsl/tokenize.xsl#L226-L244


The search page creation now uses the filter pages created in json.xsl, so that required rewriting the old filter stuff with a slightly simpler new version:

https://github.com/projectEndings/staticSearch/blob/4dddcceca579179d5240db5defe0d44f40b6a7c8/xsl/makeSearchPage.xsl#L207-L307

**Comment by martindholmes** [comment]
I believe this is all working, but I'll leave this open until I've done enough of the re-org of the JSON retrieval to be sure.

**Comment by martindholmes** [comment]
This seems to be working fine. Closing.
