### ISSUE TITLE
Score calculation bug

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#220]
What is currently SSResultSet.js line 247 is this:

return total + b.weight;

and it should be this:

return total + parseInt(b.weight);

This can cause scores of 1111111 (concats instead of sums) in certain edge-cases.

**Comment by martindholmes** [comment]
We might consider back-porting this fix to 1.4.

**Comment by joeytakeda** [comment]
Ah interesting--yes, I think we should as a hotfix

**Comment by martindholmes** [comment]
I think this only gets triggered when something else is slightly broken -- I had inadvertently deleted the wrapper div for my search-only-in controls, which resulted in an undefined for their identifier -- but we don't want it lurking.

Now, how do we do a hotfix with our current main, dev, and active feature branch scenario? Will it work to fix in dev, then cherry-pick into the other two?

**Comment by joeytakeda** [comment]
You could do the fix in a branch off main, merge it into main, release 1.4.1, then merge main back into dev, and then merge dev back into the feature branch?

**Comment by martindholmes** [comment]
Release done, but that was not the right way to do it; because I had to update the ODD/documentation in dev and main, I now have a merge conflict between dev and iss218-deletions. This convinces me that we should follow the principle we have in the past whereby in feature branches we only work on code, and we following a merge into dev, we update the documentation only in dev.

**Comment by martindholmes** [comment]
I have resolved the conflicts in the iss218-deletions branch, but we may have more issues when we try to merge that back into dev. I think the iss218-deletions branch has too much stuff going on in it, and we should get it merged asap and confine our branches to single-issue items in future. Are we done with the initial deletion work at this point?

**Comment by joeytakeda** [comment]
Thanks for doing this! It's not clear though how this was done: I'm not sure why you had to change the EDITION file? I.e. I thought it would be something like:

```
git checkout main
git checkout -b hotfix
// Fix the single line in the JS and update the documentation
git add; git commit; git push
git checkout main
git merge hotfix
git push
git checkout dev
git merge main
git push
```

In any case, I'm not sure that making documentation changes only in dev will resolve any future issues—wouldn't the conflict will just happen between main and dev, not dev and the feature branch? 

Though I agree that we shouldn't commit the built documentation—I had presumed that since it isn't in the `.gitignore` (but the other docs are), then we should be committing it, but that's not right. I'd say we should add it to the `.gitignore` and force push the HTML documentation (if we want it in the repo at all) as part of the release process.

**Comment by joeytakeda** [comment]
Re: EDITION changes--that makes sense (I suppose one could do something fancy with rebasing and replaying an old commit atop a new one, but that's always seemed like dark Git magic to me).

Since this bug has been fixed, I'm going to close this ticket (though, re-open if you think it needs to be) and open up a new ticket to discuss the generated products / documentation / release protocols—we should get those pinned down and explore options for trying to mitigate these kinds of conflicts (while I'm hoping that we have very few hotfixes that would be necessary, it seems inevitable that this kind of thing will crop up again).
