### ISSUE TITLE
Build fails if there are no filters

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#26]
In makeSearchPage.xsl, this line:

~~~~~
<xsl:variable name="filterJSONURIs" select="
        uri-collection(concat($outDir,'/filters/?select=*.json'))"/>
~~~~~

fails with an error if there are no filters in the collection, because the folder does not exist. We need a way of checking whether there are any such files before running it.

**Comment by joeytakeda** [comment]
Interesting! One quick solution I can think of is to add a “hasFilters” property to the build that we send as a param to the makeSearchPage and switch that variable to a conditional.

**Comment by martindholmes** [comment]
Yes, that would probably do it. It might be cleaner if we could detect it, though; then you could run makeSearchPage as a separate task without worrying about it that parameter.

**Comment by joeytakeda** [comment]
I was thinking that hasFilters would be detected; i.e. you could test for the existence of /filters/ in the makeSearchPage task and then send the result of that to the makeSearchPage XSLT. 

The only other solution I can think of is doing a uri-collection on the whole $outDir and seeing if some uri matches "/filters/.+.json$". But that likely wouldn't be very efficient, since it'd end up returning the URIs for all of the token JSONs too, I think.

**Comment by martindholmes** [comment]
Ah, that makes sense; use the ant available task with type="dir", then pass a boolean in.

**Comment by martindholmes** [comment]
Done and tested.
