### ISSUE TITLE
How to make static search plugin-able? (Stemmer thread)

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#40]
The static search code will need a way to handle different stemmers or plugins for Early Modern english as well as other languages. We'll need to conceive of some way that we can do that.

We could do something like allow people to use their own XSLT and function to pre-process in the config file. They would specify a file, a function, and everything else. When we process everything in the create_config_file step, we change our function call to pt:stem() to ss:stem(), which is, by default, a wrapper for pt:stem, but in the case of user-defined functions, it would call the new function instead. 

So what I'm proposing might look something like:

```
<stemmer>
<file>xsl/myNewStemmer.xsl</file>
<function_name>myFunction</function_name>
<namespace>https://example.com/someNamespace</namespace>
<prefix>myFx</prefix>
</stemmer>
```

In create_config.xsl, we modify things slightly to first allow for the new namespace:

```
<xso:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xd="http://www.oxygenxml.com/ns/doc/xsl"
                xmlns:hcmc="http://hcmc.uvic.ca/ns/staticSearch"
                exclude-result-prefixes="#all"
                xpath-default-namespace="http://www.w3.org/1999/xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                version="3.0">
<!--IF THERE IS A USER DEFINED FUNCTION, ADD THE PREFIX AND NAMESPACE HERE-->

<!--AND IF THERE IS A USER DEFINED FUNCTION, ADD THE XSL AS AN INCLUDE-->
</xso:stylesheet>

```

We'd also have to add an ss:stem function into the create_config.xsl, which by default would look like this:

```
<xso:function name="ss:stem">
<xso:param name="ss.stem.wordToStem"/>
<xso:sequence select="pt:stem($ss.stem.wordToStem)"/>
</xso:function>
```

But if there's a user defined function, we'd modify `ss:stem` to use whatever the user defined function is:

```
<xso:function name="ss:stem">
<xso:param name="ss.stem.wordToStem"/>
<xso:sequence select="myFx:myFunction($ss.stem.wordToStem)"/>
</xso:function>
```

That function could do whatever. In the case of Early Modern stemming, it would most likely preprocess the stuff and then send it back through `pt:stem`.

```
<!--In  the user defined function library: xsl/myNewStemmer.xsl-->
<xsl:function name="myFx:myFunction">
<xsl:param name="inString"/>
<xsl:sequence select="replace($inString,'foo','bar') => pt:stem(.)"/>
</xsl:function>
```

The only tricky bit here will be how to handle includes properly. If xsl/myNewStemmer.xsl includes xsl/porter2Stemmer.xsl, then we'll end up with an error, of course. The only way around that I can determine is to investigate xsl/myNewStemmer.xsl and see whether or not it includes xsl/porter2stemmer.xsl. If it does include it, then we don't include it in config. But if it doesn't, then the produced config.xsl will include it.

(Note that we could do some more sophisticated stuff with shadow attributes, but since we're creating the configuration XSLT anywhere as a pre-step, this option might be more straightforward.)

**Comment by wsalesky** [comment]
@joeytakeda @martindholmes 
I would love to be able to plug in a custom tokenizer as well/instead of a custom stemmer, if that makes sense? And it might be useful for me to be able to turn off the Porter stemmer as well. I'm happy to be a guinea pig and test this feature out.

**Comment by joeytakeda** [comment]
Thanks @wsalesky! I was just about to suggesting something similar :-)!

I think we need the tokenizer to be plugginable, and probably in the same way: rather than what we have in the `text()` template currently, it should be a function:

```
<xsl:template match="text()" mode="tokenize">
<xsl:sequence select="hcmc:tokenize(.)"/>
</xsl:template>

<xsl:function name="hcmc:tokenize">
[...]
</xsl:function>
```

We should have a configuration option for the tokenizer, which could then call other functions too, or could just call pt:stem. I think if you override the tokenizer, there's no point in overriding the stemmer, since the tokenizer will do whatever you want it to do. But if you just override the stemmer, then the tokenization process will be the same.

**Comment by wsalesky** [comment]
@joeytakeda That sounds great. Do you also run the search term through a javascript version of the stemmer? If so how would that work for pluggable tokenizers? I essentially was running the same normalization functions on the search string in the javascript as I was in the XSLT before submitting it to the application.

**Comment by martindholmes** [comment]
@joeytakeda @wsalesky One option for making things pluggable would be to have the config.xsl file include the tokenizer and the stemmer, rather than the other way round; then the config file could specify alternative versions of these files, which would be used instead. The config.xsl file would have to be reorganized considerably, though, so that it could be run with different parameters to trigger the various operations.

**Comment by joeytakeda** [comment]
But most people want the majority of the logic in those files, I think, so specifying a `mytokenize.xsl` instead of `tokenize.xsl` would mean an implementer would have to figure out which bits in `tokenize.xsl` they would want to keep in order to keep things running. Unless I'm misunderstanding?

**Comment by martindholmes** [comment]
Most people will customize by copying a file and modifying it. But we could modularize those files to make that easier.

**Comment by martindholmes** [comment]
Some decisions:

- To make the tokenizer pluggable, we need to specify that it is a function that takes a text node as input, and returns a sequence of strings interleaved with `<span class="ssToken">`.
- That function needs to be in a separate file, and we make it pluggable by having you provide the path to that file, which we then include in the stylesheet generated from the config.

In order to allow people to pre-tokenize a text collection using whatever tokenizer they like, we must:
1. Specify and document the format the encoded tokens should take.
2. Specify and document how you must store that pre-tokenized collection in a location which you then specify in your configuration file.
3. Document the fact that if you do this, your weighting etc. will still be applied, but the tokenizing step itself will not; we will simply use the tokens you've created.
4. Note that it will be an error to specify both a custom tokenizer and a pre-tokenized collection.

**Comment by martindholmes** [comment]
Some decisions on the pluggable stemmer:

- This must be implemented as an XSLT function in an external file; you provide the path to that file in your configuration file.
- There must be a parallel JavaScript tokenizer which does exactly the same thing, also configured in the config file.

**Comment by martindholmes** [comment]
Some decisions on making the KWIC customizable:

 - You can specify using a match attribute certain elements that will be ignored when constructing a KWIC. One pertinent use-case for this is when you might have old-style characters and new-style versions of them; you want searches to work using both old and new, so your tokenized text includes both contiguous to each other, but you want your KWIC to include only one of them.

**Comment by martindholmes** [comment]
@joeytakeda I'd like to split this ticket out into two separate tickets, one for making the stemmer pluggable and the other for making the tokenizer pluggable. I'd also like to propose a different mechanism altogether for this: the user can specify a folder in the config file, and any components that are found in that folder will be used in place of the default ones. 

I now have a project consisting of mixed EM French, Latin, and Wendat texts, for which no stemmer will be appropriate; only wildcard searching makes sense, and now we have that, we can make use of this project to work on this ticket in a particularly convenient way. What's required for this project is stemming that does nothing, something that @wsalesky also asked for. Rather than create a mechanism to turn stemming off, I think it would make more sense to plug in stemmers that do nothing; that way we can develop the plugin capability without having to work on an actual stemmer at the same time. Then after that I can work on the French stemmer for the Mariage project without worrying about the plugin mechanism.

I think we should separate out the stemming pluggability from that of the tokenizer, because the former is going to be commonly overridden, but the latter rarely. If we start with stemming, we can tackle the more difficult issue of tokenizing later; that will require some modularization of the tokenization process.

f we rename our porter2stemmer.xsl to ssStemmer.xsl, and our ssPorter2Stemmer.js to ssStemmer.js, we could allow the configuration file to contain the path to a folder in which the stemming components are found. These files would bear the same name as the default ones, and would just be included instead. 

So if the user specifies their /mystemmer/ folder, the config will include any files found there instead of the defaults; any files which are not there would remain as the defaults. (So you could, if you wanted to, put your own XSLT stemmer in but ignore the JS stemmer and get the default there; that would be silly and would break things, but it's not really our business.)

We could provide the default files in a folder called stemmer_en, and pull them from there; we could provide a second folder called stemmer_none, which has implementations which simply return the token unchanged, and anyone wanting to turn off stemming could simply use those. The Wendat project would work as proof-of-concept for this functionality. Any user wanting to develop their own stemmer would have virtually empty framework files in stemmer_none to get started from. When I develop the French stemmer, I can add that to the project in stemmer_fr.

We have also talked about a pre-stemming step, which would be used to pre-treat early modern English or French to prepare it for processing by a modern stemmer. We could simply do that by creating yet another pair of stemmers based on the modern ones but with an added step; or we could introduce ssPreStemmer.(xsl|js) files into those folders, with the default ones simply returning the token unchanged. I'm not sure which is the cleanest approach there.

Thoughts?

**Comment by joeytakeda** [comment]
This all sounds like a good plan to me and especially beginning with an identity stemmer, since that will be trivial to implement as a stemmer but will be a perfect test case for actually making this plugginable.

It will be some significant refactoring, but that's worth doing anyway--obviously it will need its own branch. I do think that once the stemmer is made plugginable, the tokenizer will be fairly simple to add in as well into the XSLT at least.

**Comment by martindholmes** [comment]
Thanks @joeytakeda, I'll go ahead with this. I'm thinking of a folder structure like this:

stemmers/en/stemmer.((xsl)|(js))
stemmers/donothing/stemmer.((xsl)|(js))

so it's really explicit.

**Comment by martindholmes** [comment]
@joeytakeda I started this work thinking that I would make the configurable path to the stemmer folder relative to the location of the search page (i.e. based on the location of the user's project), but for the vast majority of cases I think that's way more complicated than it needs to be, since most people will probably be using our stemmers. So I propose to make that configuration item simply a folder name, expected to be in the project basedir /stemmers/ folder. So the default value would be "en", and you might change it to "donothing" to get the zero stemmer, or "fr" to get the French stemmer when we write it. People creating their own stemmers can simply put them there, and/or contribute them to the project and we'll put them there. Does that sound OK?

**Comment by joeytakeda** [comment]
My immediate concern is that it prevents people from simultaneously making whatever esoteric stemmer they might want for their project while also keeping their repo up-to-date whenever they run a build process if they delete and re-checkout the staticSearch repo in every build (like we do). 

On the other hand, I see your concern here with the stemmers being in any random place on disk since that makes resolution really difficult because of the different contexts of resolving in the XSLT and resolving the URI for the javascript. Plus, the number of esoteric stemmers is probably quite small; it's more likely that people will write a stemmer that may be of use to others and thus we should keep it in our repository too.

In sum: I agree with your approach above. I think if someone may need some sort of esoteric stemmer (probably no one will) and they want to refresh the static search repo with every build, then they simply need to ensure that their stemmer ends up in the staticSearch/stemmers/ directory (running a `cp` beforehand or whatever).

**Comment by martindholmes** [comment]
Thanks Joey; I've gone ahead on that basis, and I have a preliminary implementation working in the branch (issue_40_pluggability). It turned out to be slightly gnarly because you can't just use a variable from a prior xsl:include in a second xsl:include/@_href, so I've had to add the inclusion of the stemmer in the config.xsl file. The test repo builds with no specified stemmer folder (i.e. the defaults work); tomorrow I'll create the donothing stemmers and test with those.

**Comment by joeytakeda** [comment]
That all sounds good to me. A few questions that I've just thought in terms of the folder naming and structure:

* Should we include both porterStemmers since we have them anyway? 

* What sort of stuff is allowed in the `<stemmerFolder>`? Can people nest stemmers, for instance (eg: `/stemmers/en/porter2`, `/stemmers/en/porter1`)? Or should we just constrain the value of `<stemmerFolder>` such that it must be a good*  directory name?

And I will say that I personally would prefer `identity` over `donothing` as a stemmer name, but that's purely stylistic preference :-) 

<hr/>

\* Where "good" is up for debate: I'd probably say no punctuation at minimum except underscores, dashes, and dots.

**Comment by martindholmes** [comment]
The way I've set it up, it expects two files, ssStemmer.((xsl)|(js)). The Porter 2 stemmer is in a folder called /stemmers/en/. I don't think we have a porter 1 stemmer in JS, and there's no point in the XSLT one unless there's a matching JS one, is there? I'm not sure what the benefit of nesting will be, unless you're collecting multiple stemmers for the same language, and I think it'll be more important to provide stemmers for multiple languages. As it stands, the `<stemmerFolder>` element content is NCName, so nesting won't work, but if/when we get to a point where we have multiple stemmers for the same language, we can revisit that easily enough; I think the existing code would work with nesting, but the schema would need to be changed.

I do prefer /identity/ over /donothing/, but its function will be less obvious to people who don't write transformations. I wonder if we can come up with something that makes the function clear to non-specialists but sounds more formally accurate.

**Comment by joeytakeda** [comment]
Re: nesting— that sounds completely fine with me. I glanced at the schema but didn’t see you had already defined it as NCName, so my mistake there. 

Re: identity vs donothing vs something else: I think identity is understandable, especially so long as we define it in the documentation. Plus as you note, it’s already a standard term in ANT or XSLT,  so it’s immediately recognizable by users familiar with either of those languages. We could even link to the “identity transform” Wikipedia page, which gives a nice and generic definition: https://en.m.wikipedia.org/wiki/Identity_transform

**Comment by martindholmes** [comment]
OK, I'm convinced. Identity it is. I'm just testing with MyNDIR and DVPP right now, and if those are good, then I'll issue a pull request for you to look at, without the identity stuff. Then I can build and test the identity stuff in the issue 40 branch working with the Wendat project, which needs it, and do a second pull request when I'm sure that's working.

**Comment by joeytakeda** [comment]
@martindholmes , you say earlier that:

>  I'd like to split this ticket out into two separate tickets, one for making the stemmer pluggable and the other for making the tokenizer pluggable.

I don't think we did this, but we probably should. I would say that this this ticket could be renamed "Make stemmer pluggable" and then could be closed (since I think all of that work is now done and tested). We should make a new ticket--Make tokenizer plugginable—and add it to the 1.1.0 (or whatever we decide in #54 ) milestone. How does that sound?

**Comment by martindholmes** [comment]
Perfect. Will do.

**Comment by martindholmes** [comment]
This work done; follow-on issue is #70.
