### ISSUE TITLE
Should hyphenated terms end up in the non-dictionary list?

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#5]
The new handling for hyphenated terms results in many of them ending up in the list of non-dictionary words. Would it be better to add them only in cases where one of both of the component terms are not in the dictionary?

**Comment by joeytakeda** [comment]
yes, I think you’re right. The handling will have to be slightly different though. Rather than check the notInDictionary data attribute on the actual full hyphenated term, the report XSLT should find hyphenated terms (I.e a staticSearch token with SS token children), and if every token is not in dictionary, then add it to the list.

**Comment by joeytakeda** [comment]
@martindholmes This should be handled now. Though, now that I return to this ticket, I realize I misread your above comment as saying that when _all_ component terms are not in the dictionary, then add the hyphenated thing to the not in dictionary list in the report. 

But I think it should (as it now does) investigate all the terms and only add if all the terms aren't in the dictionary, since words can be smashed together with hyphens arbitrarily, no? What do you think?

**Comment by martindholmes** [comment]
I don't think I was clear in my original post, but I think you're right: let's go with adding fewer things to the list, since it tends to get pretty big anyway.

**Comment by joeytakeda** [comment]
Fixed in https://github.com/projectEndings/staticSearch/commit/2063bf43c788017bc3664f9fc8b94e8c639b075b and so closing this issue.

**Comment by joeytakeda** [comment]
As reported by GN, this behaviour has regressed: it should be re-added into the reports.

**Comment by joeytakeda** [comment]
This should be fixed now with the rest of the reporting stuff.
