### ISSUE TITLE
Another refinement to sorting

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#58]
The Colonial Despatches site has a desc filter for Archival Id which has content like this (and this is the order they currently sort in):

~~~~~
CO 305:1
CO 305:10
CO 305:2
CO 60:1
CO 60:10
CO 60:2
~~~~~

A more sane sort order would be:

~~~~~
CO 60:1
CO 60:2
CO 60:10
CO 305:1
CO 305:2
CO 305:10
~~~~~

There are two possible ways this could be achieved: the XSLT could try its cunning best to figure out how such random sequences should best be sorted, perhaps by breaking them down into components and sorting sequentially on each component, after determining whether it's numeric or not; or we could choose to support a sort key on the meta element, so the original begetter could generate e.g.:

~~~~~
CO06001
CO06002
CO06010
CO30501
CO30502
CO30510
~~~~~

since they know the structure of their data. The former approach would be fun to implement but not necessarily successful in many cases; the latter would be relatively easy.

**Comment by joeytakeda** [comment]
I'm in favour of the sort key approach, since that could also be re-used at some point for sorting the docOnly results (#51) -- you could specify which field (i.e. title or maybe date) as your sort key in the config or something and then we'd already have that information keyed to the documents. 

If we decide a sort key mechanism, do we need to have some sort of typing or do we just say that if the thing is castable as an integer (or float?), then we sort it like an integer value, otherwise we sort it as a string?

**Comment by martindholmes** [comment]
I think we're already doing that (https://github.com/projectEndings/staticSearch/issues/41). It would just be a question of checking for a sortkey and using that instead of the text contents if it's there. Mostly where a sort key is needed it'll be an alpha sort, I think, but some users might just generate a sequence number.

I'm not sure that result sorting should be mixed up with filter control sorting, though. We'll need to think about that a bit.

**Comment by joeytakeda** [comment]
Yes, you're absolutely right--I was mixing up the filter option sorting with the actual document results.

Is the idea then that users could provide a data attribute for sorting? I.e.

```
<meta name="Archival ID" class="staticSearch.desc" value="CO 305:1" data-sFilterSortKey="CO30501"/>
```
?

We'd then have to add the sortKey to the filter JSONs so that they're readable by the searchPageCreation bit, I believe.

**Comment by martindholmes** [comment]
Yes, that's the sort of thing I was thinking. But I don't think they need to be added to the JSON, do they? We only need that info when creating the control, which is a one-time offline thing. If that's done based on the JSON (I can't remember), then we could post-process the JSON to drop the info afterwards, so we don't have unnecessary weight in the download.

**Comment by joeytakeda** [comment]
The search page is based on the JSON, so we would potentially have to post-process the JSON unless we think of something else.

Another option is that we store that data implicitly in the JSON itself by doing all of the sorting for the input options in the JSON itself. So somewhere around here:

https://github.com/projectEndings/staticSearch/blob/edf4bf0ca8f4ff96708966fd6bc357e7efcf7b96/xsl/json.xsl#L513-L531

We could add sorting to the for-each-group on L513, which could do all of the sorting for the JSON at that point, and then the search page just needs to follow the structure of the JSON for creating the options in the search.

**Comment by martindholmes** [comment]
I think we'd do it in makeSearchPage.xsl, no? We're already sorting the controls there:

https://github.com/projectEndings/staticSearch/blob/dev/xsl/makeSearchPage.xsl#L300

**Comment by joeytakeda** [comment]
Yes, but we create those controls from the JSON files, so the only way we'd know their sort keys is if we put in the JSON file. So, in my mind, there are two approaches if we use a user-defined sort key:

1. Add the  sort key to the JSON, process it in makeSearchPage, and then re-process the JSONs to remove the sort key to remove it
1. Do the sorting in the JSON creation stage and then in makeSearchPage just process the filters in the order they appear 

I like option 2 since it doesn't mean adding another step in the build and would make the search page creation step simpler, but it is a bit more complicated.

**Comment by martindholmes** [comment]
Agreed. Before we proceed, though, we should consider whether there is any cunning algorithm we could come up with that would actually give the expected "sensible" result automatically. For example, could we tokenize on every non-alphanumeric character cluster, and then, for each of the resulting tokens, determine whether it's numeric or alphabetic, and then do a progressive sort? Or should we tokenize at alpha/digit boundaries too? We might end up with:

CO305 20:2
CO305 20:10
CO60 20:10
breaking into:

CO / CO / CO
305 / 305 / 60
20 / 20 / 20
2 / 10 / 10

which would sort to:

CO 60 20:10
CO 305 20: 2
CO 305 20:10

which would be the desired result in this particular case. How generalizable is that? We'd lower-case alphas of course. What would we do at point boundaries between digits -- assume a decimal, or break into two integers? Would we drop initial determiners -- which is language-specific? Or is this completely infeasible, and a sort key is the only practical solution?

**Comment by joeytakeda** [comment]
I like this idea, but I think we'd want something as generalizable and usable as possible in cases where there's no implicit order that can be derived from the names themselves. For instance, the Static Search documentation filters had to be re-ordered using flex to make it sort Basic, Intermediate, Advanced and the WEA search reorders the filter descriptions for exhibits to follow the narrative order of Eaton's career (Early Experiments, New York, Japan, Alberta, Hollywood).

Of course, we could have it both ways: have the cunning sort mechanism you propose, which will work for a number--but not all--purposes, and then also suggest that people re-order the checkboxes however they wish in their own implementation: they could re-order them in another build step or using Javascript on page load or using CSS flex. (Though I have my own concerns about CSS flex re-ordering: it is meant to change only visual order and not tab order [though FF does change the tab order but it's considered a bug!]: https://tink.uk/flexbox-the-keyboard-navigation-disconnect/)

**Comment by martindholmes** [comment]
I hadn't realized that flex reordering left tab order intact. That sounds a bit weird. For me that's the final nail in the coffin for the idea that we should encourage people to use flex to sort. We need to provide a mechanism.

Let's start by implementing the cunning sort algorithm and see how many cases it works for, then if there are glaring problems in any of the projects, implement the sort key.

This is a slight distraction from the work I should be doing on wildcards, but that's paused because I'm not able to get sufficiently long blocks of dev time, and the wildcards needs some proper concentration, but also because I'm a bit worried that there's an inherent limitation in our approach there -- there are definitely cases where a legitimate wildcard token will not match the stemmed version of the intended term that appears in the ssTokens file because of the distortion of form introduced by stemming (/fancy*/ vs fanci). I'm not sure how bad a problem that actually is, but I wish I could solve it.

**Comment by martindholmes** [comment]
I've done some playing around with the cunning approach today, and I don't think it's going to be really useful. There are too many potential issues. For one thing, it sort of assumes that all strings to be sorted will consist of the same number of components when they're split on non-alphanumerics, and that's plainly unlikely; when it's not true, you can end up sorting integers against strings. So on balance I think a sort key is the sensible approach. We can implement and test it with our documentation build, and do away with the flex component.

**Comment by joeytakeda** [comment]
That sounds like a good plan to me. So, just to remind myself what we were thinking here:

* There'd be something like this in the XHTML document:

```
<meta name="Archival ID" class="staticSearch.desc" value="CO 305:1" data-ssFilterSortKey="CO30501"/>
```

* In the JSON processing for the filter files, we put them in the JSON in their proper order based off of their data-`@ssFilterSortKey`.  My assumption here is that we try and use a sortKey if it's there but fallback on the value otherwise, right?

```
<xsl:sort select="if (@data-ssFilterSortKey) then @data-ssFilterSortKey else @value"/>
```

* When we create the search page, we process the filters in the order that they appear in the JSON.

**Comment by martindholmes** [comment]
That's definitely a good starting point. I fear that the way I'm merging the filter data in the JS may obviate the JSON sequencing, though, because I'm using sets. We'll see. It would be nice if we could avoid having to add the sortKey to the JSON.

**Comment by joeytakeda** [comment]
I don't think this will affect the Javascript or JSON at all, since we're just wanting to modify the appearance of the search page; I don't think it matters whether the JS cares about ordering at all. 

And what I'm thinking is that we won't need to add any data to the JSON at all. When we produce the JSONs from the `<meta>` tags, we sort the values for that filter; when we make the search page, we can just read the JSON and add the filter values in the order that they appear (which will simplify the search page creation quite significantly or at least move that complexity to the JSON step).

Have you started on this already? If not, then I'm happy to work on this in another branch.

**Comment by martindholmes** [comment]
Yes, you're right, I'm confusing two things: the need to have a sort key by which results can be sorted (for example, Despatches wants to sort results by date, even if the date filter is not used in the search) and the need to sort the descriptors in filters. Please go ahead and do latter; we'll have to think a bit about the former. 

I wonder if we might have a global search-results-by setting which would allow you to specify an existing filter...

**Comment by martindholmes** [comment]
I've just added a process to generate a sort key for the Archive Record desc field in the Despatches project. If that builds OK, we'll have a dataset to test with.

**Comment by martindholmes** [comment]
We now have a working dataset, and I'll add something similar into the test data for quick testing, and look at implementation. This should be the last new feature for 1.0.

**Comment by martindholmes** [comment]
I'm now working on this in branch issue_58_sort_key. It's not as simple as we thought, because the sorting we do now in the rendering of the search page controls is quite sophisticated; it checks to see whether the content is numeric or not. We need to preserve that behaviour for cases where there's no sort key, and we also need to allow for situations in which there's a sort key for some items but not for others (which would technically be an error, but we can't prevent it). So I'm taking a slightly different tack; I'm going to add a sort key to the JSON, either using the supplied sort key if there is one, or using the plain content if there's not, and then sort with that sort key instead of the content in the search page construction, but retaining our existing discrimination between numeric and non-numeric content.

**Comment by martindholmes** [comment]
I've now tested this locally with the Keats site, and Jenkins is building the Despatches site as an additional test. I'll create a pull request for the changes.
