### ISSUE TITLE
Multiple error triggers confusing

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#65]
If you do a search for `illustrated by` (no quotation marks), you get two error messages:

1) The alert: "Your search is too broad. Include more letters in every term. (by)"
2) The browser error for the `@pattern` (for me in Chrome: "Please match the request format")

But you still, of course, get results because of the 'illustrated' since only "by" was problematic, not the whole thing.

Since the search continues on even with the errors, I think we should be more forgiving with the error messages we output, since they are, at least to the end user, more like warnings than actual errors that stop the process entirely.

Two options in my mind:

1) If we want to provide a different default behaviour, I'd say we should accumulate these warnings and put them before the results div so that it's clear someone bad happened, but that the process was able to continue on.
2) We make the warning function a property (i.e. `this.functionOnError`) or something that by default is the alert, but could be overridden by the JS implementer so they could do whatever they want with it.

What do you think?

**Comment by martindholmes** [comment]
I tried hard to come up with a way to signal what the problem was with short terms, but not prevent the search from going ahead; I thought this was the solution we agreed on, but perhaps I'm misremembering. Does the browser pattern also raise an alert on your Chrome? On my Chromium, it just gives you a mouseover message on the text box warning you that your search is still not correctly formatted. In other words, there is only one warning I'm responsible for (the alert), and the other is just a gentle nudge from the browser that the search string (still) doesn't represent a legitimate search, persisting until you change it.

Do you think we should get rid of the pattern check completely?

**Comment by joeytakeda** [comment]
Originally I thought the alert thing was just for wildcards, so that was my misunderstanding! 

The pattern check doesn't give an alert, but a popover thing over the input. My original thought was that adding an `@title` to the search would provide a better search message that explains what the "request format" is, but that doesn't seem to be  to differ by browser. I added a `@title` locally and here's what I've found from testing. 

**Chrome**: `@title` displays as text after the default "Please match..." message; displays a popover that sticks to the input, which cannot be dismissed but fades after a few seconds. 
![Screen Shot 2020-07-19 at 2 40 50 PM](https://user-images.githubusercontent.com/17664763/87885948-128e8f00-c9ce-11ea-99c2-220e5767707d.png)

**Firefox**: Warning is displayed only when hovered (like normal `@title` behaviour), but `@title` overrides the default message; the input focus red if there's an error:
![Screen Shot 2020-07-19 at 2 48 46 PM](https://user-images.githubusercontent.com/17664763/87886068-fa6b3f80-c9ce-11ea-855d-6acb445fe0a2.png)

**Safari**: Ignores `@title` completely, doesn't change the appearance of the box, and, most annoyingly, the message is dismissed as soon as you scroll, so the message is gone by the time you scroll back up to the input box after the results are displayed

![Screen Shot 2020-07-19 at 2 47 09 PM](https://user-images.githubusercontent.com/17664763/87886031-bf690c00-c9ce-11ea-89d7-6522cfeef6c5.png)

So yes, I think we should remove the pattern check, since its behaviour seems to vary so wildly between browsers and there's no simple way to add a useful warning for people.

In terms of the alert: I don't love the alert mostly out of personal preference: I find them sort of abrasive and they display particularly badly on Chrome (though I like how Firefox and Safari handles them). In terms of whether or not we want to take any action on this, I think my preference would be to make that error handling thing a customizable function so that, by default, people get the error message, but the intrepid user could change that behaviour to do whatever they want it to do, if they so choose.

**Comment by martindholmes** [comment]
So:

1. Remove the pattern check completely.
2. Harvest all the warning messages for terms not used in the search (which could also include stopword terms).
3. Display those messages above the search results, or instead of them if no search ends up being performed.

Does that work? 

Incidentally, any method of the object is hookable; you can just replace it with your own version after instantiating the object. But because these errors are triggered at different points in quite complicated and lengthy functions, it would be a bit messy to abstract them at the point they're generated; I was thinking I'd accumulate them in an array, and then process that array. It's easy to make the one-line thing that writes out the errors to the results into a method you could hook, so you could process that array any way you like.

**Comment by joeytakeda** [comment]
That sounds like a perfect solution to me!

**Comment by martindholmes** [comment]
@joeytakeda Could you test the solution in the issue_65_discarded_terms branch to see if it works as intended?

**Comment by joeytakeda** [comment]
@martindholmes : works perfectly! I added one small thing: a `@class` value of "ssDiscarded" to the para to make it easy for implementers to style if they so choose.

**Comment by martindholmes** [comment]
That works for me. Shall I merge?

**Comment by joeytakeda** [comment]
Yep! Thanks!

**Comment by martindholmes** [comment]
Done!
