### ISSUE TITLE
FR: Consider tf-idf relevance scoring

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#67]
Speaking with my colleagues at SFU about this project and one asked about our scoring algorithm and whether we rank by relevance. I hadn't thought of that before, but relevance scoring seems like a good thing to add to StaticSearch for a couple reasons. 

First is that for digital editions with documents of vastly varying lengths, long documents (like novels) will almost always appear before anything else, thus completely overwhelming short texts like poems or short stories that may feature the word relatively heavily, but not compared to a novel.

Second is that other search engines used for DH projects, like Lucene, have relevance scoring baked in;  Lucene uses a modified version of tf-idf (https://lucene.apache.org/core/3_5_0/api/core/org/apache/lucene/search/Similarity.html) which is very complex, but I think we could do something a bit simpler while still getting good and consistent results. 

So my feature request here is to add tf-idf scoring to the JSON files as described by https://nlp.stanford.edu/IR-book/html/htmledition/tf-idf-weighting-1.html: 

```
tf-idf = ($instancesOfTerm / $totalTermsInDoc) * log( $allDocumentsCount / $docsWithThisTermCount )
```

In terms of what constitutes a "term" for us, I'd say we use the stem as a term; and the total terms in the document would be the total number of distinct stems found in that document. Weighting would be handled as an instance of a term: so a span with a weight of 2 would simply count as 2 instances of that term.

We already have most of this information contained within the various groups that create the JSONs, so we could create tf-idf scoring without adding complex steps to the JSON (other than adding a few `count()`s and doing the actual calculation). And since we we won't need to do any additional tree traversal (except to get the total number of terms in a single document, which could be made into a cached function based on document-uri), I doubt that there would be much of a significant performance impact. 

In any case, I think this should be probably be an opt-in thing, rather than a default change. We could add a configuration option called `<relevanceScoring>` (or something) that would be a boolean value. In terms of implementation, there are two options in my mind for when `<relevanceScoring>` is set to true:

1) In the XSLT, replace the raw score with the tf-idf as the value for `<number key="score">`. That would mean no changes at all to the Javascript or the search interface.

2) In the XSLT, add a a new `relevance` key value to the JSON with the tf-idf value. Then the Javascript can use either the raw score or the relevance ranking depending on a user configured option in the search form (e.g. Sort by: Relevance or Score). 

I'm loathe to add another thing by default to the search form since it's already quite complex (and another thing in the query URL), so I think I'd prefer the first option, if this seems like a worthwhile thing to do. @martindholmes : What do you think?

**Comment by martindholmes** [comment]
@joeytakeda I agree that this is doable, and not actually too complicated. The last time I looked at tf-idf scoring, I was unable to find any research that demonstrates that it has any correlation with human intuition about relevance. That may have changed in recent years (or I may not have been looking in the right places), but when I was working on this stuff around 2012, I found it rather analogous with similarity metrics; there are lots of metrics, but there's no real evidence that any of them align with similarity as perceived by humans -- partly because it's remarkably difficult to measure such a thing. 

If there is good evidence that tf-idf aligns with human intuition, we should just adopt it by default; if not, then maybe it should be optional. But I think we have an awful lot of optional things already. I'd rather come to a decision that it's better, based on evidence, and then just adopt it, if that's possible.

**Comment by joeytakeda** [comment]
That's a good point and definitely worth researching. I do think the full count of how many instances of something there are in a document is useful information for someone performing a search (esp. since the KWICs are limited to whatever number), but that's simple enough to append at the end of the KWIC list, for instance, if either we or the implementer wanted to.

In order to experiment with this and see test the results, I've created a branch with a basic implementation of the algorithm as the score: [iss67-tf-idf](https://github.com/projectEndings/staticSearch/tree/iss67-tf-idf). I looked at the test page, but it doesn't provide a great example since a) there isn't much text in the first place and b) the page itself breaks since the test fail instantly because the score has changed. But here's an example of what you get when you search poem:

![Screen Shot 2020-08-01 at 12 09 57 AM](https://user-images.githubusercontent.com/17664763/89096439-990e7d80-d38b-11ea-91a7-abac7a44d566.png)

I'll continue to experiment with the other projects and do some research into this as well.

**Comment by martindholmes** [comment]
Those results are a perfect example of why I find this stuff difficult to trust. The home page has more about poems than the initial search page, but because the initial search page happens to be short, it gets top billing. A short page which says "this has nothing whatsoever to do with poetry" would win out over a largish encyclopedia which contains an article specifically about poetry. The math looks plausible till you start to think about actual humans and actual texts.

**Comment by joeytakeda** [comment]
> A short page which says "this has nothing whatsoever to do with poetry" would win out over a largish encyclopedia which contains an article specifically about poetry. 

I agree with this, but the converse also is true: for projects like the WEA with a varied collection of novels and short stories, the raw score gives a statistical advantage to longer texts since it's just more likely that a novel will contain more instances of a a term, especially for common phrases or thematic keywords. 
 
For instance, a search for `garden` in the WEA using the raw score returns the following as the top six hits:

* Daughters of Nijo [Novel] (59 instances)
* A Neighbor's Garden, My Own, and a Dream One (Part 1) [Short story] (40 instances)
* A Neighbor's Garden, My Own, and a Dream One (Part 2) [Short story] (40 instances)
* A Japanese Nightingale [Novel] (24 instances)
* Sunny San [Novel] (22 instances)
* Japanese Blossom [Novel] (20 instances)

A search using tf-idf returns:

* A Neighbor's Garden, My Own, and a Dream One (Part 1) [Short story: 2nd in raw score]
* A Neighbor's Garden, My Own, and a Dream One (Part 2) [Short story: 3rd in raw score]
* Daughters of Nijo [Novel: 1st in raw score]
* Amoy, A Chinese Girl [Short story: 13th] (7 instances)
* The Marvelous Miniature Trees of Japan [Ethnographic article: 14th in raw score] (6 instances)
* Home Life of the Japanese Woman  [Ethnographic article: 20th in raw score] (5 instances)

Amoy, A Chinese Girl is set primarily in and around a tea-garden; The Marvelous Miniature Trees of Japan and Home Life of the Japanese Woman are ethnographic texts that attempt to describe Japanese gardening practices. So both are obviously about gardens more than Sunny San, which is a 311 page novel primarily about the university that just happens to mention gardens more times.

So I'm still a proponent of using tf-idf but I don't think it's something that should really be adopted for every project precisely because of the concerns you note above.

**Comment by martindholmes** [comment]
Agreed. My own gut feeling is that it's "wrong" as often as it's "right" (in terms of providing the results that a human actually wants); at the same time, regular users are perfectly well able to understand that a longer text is likely to have more instances of something, all else being equal, and take that into account when they're parsing their search results, but they'll often be puzzled by weird result sets from tf-idf because they don't know why they're happening. Let's make it configurable then. 

In terms of your excellent example, I would suggest that if the searcher is looking for what collocates with "garden" in the WEA texts, then they probably do want the novel first, because it has lots of instances. In other words, people are not always searching for a "topic", whatever that is; sometimes they're searching just for words, because they constructed the "topic" by combining a group of likely search terms, or because they don't care if a text is "about" something, they just care if it contains it.

**Comment by joeytakeda** [comment]
I agree--it's certainly not the golden algorithm for scoring, but it is effective in a number of cases.

I've now made this configurable in the iss67-tf-idf branch and tested in the WEA and will make a PR.

**Comment by martindholmes** [comment]
This now seems to be working well. Any reason not to close it? Should the long floats showing as scores be massaged in some way to avoid frightening users, or will nobody notice the scores anyway?

**Comment by joeytakeda** [comment]
The tf-idf score is sort of meaningless to humans, I'd say. We could add a `<span>` to the score, so that if someone is doing tf-idf, it's trivial for them to hide it if they don't want to show it.

**Comment by martindholmes** [comment]
If you hide it completely, though, people will puzzle over how the results ended up in the order they're in. I was just wondering if it might make sense to round it a bit, or something like that. But your call on this one. :-)

**Comment by martindholmes** [comment]
@joeytakeda Any action left to take on this one?

**Comment by joeytakeda** [comment]
I've just added a `<span>` around the score caption to make it easier to target with CSS or JS if someone wants to modify it in whatever way (hide it, make it a different font-size, take the stuff after the score caption and truncate it, et cetera). But otherwise, I think this is done.

**Comment by joeytakeda** [comment]
I'm going to close this ticket now since I believe this is done, but feel free to shout if you think otherwise :-)
