### ISSUE TITLE
Valid HTML structures cause error in hcmc:returnContext()

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#7]
The DVPP project has a `<span>` element as the first child of `<body>`; it's the bit containing the "BETA" warning on pages on dvpp.uvic.ca. That's valid HTML5, but it causes the json generation to fail here:

https://github.com/projectEndings/staticSearch/blob/master/xsl/json.xsl#L349

I don't think it should cause an error; a text node for which a context can't be calculated can just have a context derived from its own content. But I'm not sure what the best way to handle this would be. What do you think?

**Comment by joeytakeda** [comment]
I think this is actually a bug in the how we determine context nodes. By default, `div | blockquote | p | li | section | article | nav | h1 | h2 | h3 | h4 | h5 | h6 | td` are context nodes, unless others are specified. But we should probably add `<body>` as a default context ancestor as a fail-safe, since, by definition, `<body>` must be in the file. Does that work?

**Comment by joeytakeda** [comment]
https://github.com/projectEndings/staticSearch/commit/1af02f006538dca19a83e59c74a3a4d954e4a2c5 adds body to the list of default elements for the context ancestor bit and adds a `<span>` as a child of `<body>` in the contexts.html page to test.

**Comment by martindholmes** [comment]
I'll test as soon as I can, and close the ticket if it's fixed. Thanks Joey!

**Comment by martindholmes** [comment]
Fixed and working.
