### ISSUE TITLE
Need to prefix property names

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#79]
It would help to avoid naming collisions if we prefixed all our ant property names in case people are calling our ant build processes from within other ant builds.

**Comment by martindholmes** [comment]
I think the best approach here might be to avoid using a prefix ending with a dot (which is a standard way of prefixing e.g. environment or runtime properties) and just name our properties with a leading ss, so that 

`<property name="saxon" value="${basedir}/lib/saxon-he-10.jar"/>`

becomes

'<property name="ssSaxon" value="${basedir}/lib/saxon-he-10.jar"/>`

and 

`<property name="config" value="configTest.xml"/>`

becomes 

`<property name="ssConfig" value="configTest.xml"/>`

**Comment by joeytakeda** [comment]
One think that we will need to think about before implementing this is backwards compatibility. My builds, for instance, set the `${config}` when they invoke staticSearch, so they will all break if/when they update to 1.1 since `${config}` will no longer exist.

If we want to ensure backwards compatibility, then one thing we could do is stage this so to deprecated the old values; we could duplicate the properties, so that config, for instance, is really just an alias for ssConfig:

```
<property name="config" value="configTest.xml"/>
<property name="ssConfig" value="${config}"/>
```

We could then check to see if the non-prefixed and prefixed properties are the same value; if they are, then that means the implementer has used the non-prefixed version, and we then give them a warning that those properties are going to go away in 1.2.

**Comment by martindholmes** [comment]
I think that makes sense.

**Comment by martindholmes** [comment]
@joeytakeda This needs a careful implementation plan, as well as well-defined deprecation methods/approaches, so I think it should wait till 1.2, and before it's done, our policies and mechanisms for deprecation should be clearly articulated and implemented.

**Comment by martindholmes** [comment]
We've just hit a genuine case where Greg had a build file fail because he was defining a `${saxon}` property in his build file, then calling the staticSearch build file, which has the same property, so it was being overridden with the one from his file.

So for 1.2, I really think we need to do the deprecation-with-warning thing, and then as soon as that's out, remove the old stuff entirely from dev.

**Comment by martindholmes** [comment]
Made a start on this by prefixing ssSaxon. I'll work through all the non-problematic ones -- properties that would normally not be set externally -- and then we can deal with config and any others that might need graceful deprecation later. I don't think this needs a branch (yet at least).

**Comment by martindholmes** [comment]
I think all straightforward ones are done; what's left is the config-related stuff and the headless property, which I explicitly set in my builds.

**Comment by joeytakeda** [comment]
I think the headless property can be deprecated—we only used it when auto-opening files, and since we don’t do that anymore, I don’t think we need to keep it around at all.

**Comment by martindholmes** [comment]
Ah, good point. For the config one, I thought we could actually pause the build and get the user to press return to carry on, so that we know they've seen the message, and they can actually fix it right then. It should also go into the report, of course.

**Comment by martindholmes** [comment]
Now working on the remaining stuff in branch issue-79-prefixes.

**Comment by martindholmes** [comment]
@joeytakeda After a fair bit of testing and playing around, I've decided that I think we should simply abort the build if people are still using the old parameter names and show them an explanatory error message. There seems to be no reliable way to fail gracefully; if you require user input to proceed with a build, then things will go badly wrong on a build server; if you just issue warnings as the build goes on and put error messages in the report, then most people will never see them. I'm going to just make the build fail so people have to fix the problem; we can add big warnings to the What's New page as well. Better to bite the bullet now, while there's a tiny number of users, and force ourselves to fix all our own projects immediately, I think.

**Comment by joeytakeda** [comment]
Sorry for the delayed reply here! 

Now that I think about this a bit, though, is there any reason why we shouldn't simply recommend people call the build with `@inheritAll = "false"`? If you call the build doing that, then there's no way that there would ever be a collision with property names.

**Comment by martindholmes** [comment]
I think that's a bit of a cop-out -- we can't be bothered to avoid property names that are so common there are bound to be collisions, so it's up to you to do that avoiding. And there may be lots of contexts -- complicated ant builds with lots of inclusions, for instance -- where it's not straightforward to do that. It's better to try to be a good citizen than teach people how to work around your badness.

**Comment by joeytakeda** [comment]
I wouldn’t say this is *our* badness, but a badness of ant itself.  At the moment, one has to specify inheritAll = false since we’re using $basedir to resolve Saxon and point to our XSLTs, which will almost certainly fail in other projects if inheritAll isn’t set— it will be the caller’s basedir unless inheritAll is false (or some other complex set of attribute combinations are met: https://ant.apache.org/manual/Tasks/ant.html). 

So if we do want to take an opinionated stance against that, then I think we will also need to also have our own ssBaseDir, which would always be the directory that contains the staticSearch build, and use that exclusively.

**Comment by martindholmes** [comment]
That's a good point -- I hadn't thought about ${basedir}. I'll add that into the mix. Ideally, whether people think hard about this or not, things should just work, and it's likely that our stuff is going to be run at the end of a long and potentially quite complicated site build.

**Comment by martindholmes** [comment]
I've set up a local basedir, which works nicely. Can you think of anything else?

**Comment by joeytakeda** [comment]
No I think that all looks good to me—shall I merge the PR into dev?

**Comment by joeytakeda** [comment]
Actually, @martindholmes , since you have the most projects that will break when this is merged, it makes most sense for you to merge it when you have a chance to do so. I can just switch LOI and WEA whenever it’s merged in.

**Comment by martindholmes** [comment]
Thanks @joeytakeda. I'll merge it some time this weekend and churn through the projects switching them all over.

**Comment by martindholmes** [comment]
Done and dusted.
