### ISSUE TITLE
`docs.json` needs to include document titles

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#8]
When a user does a search without any actual search terms, just using the document filters (which I think is perfectly valid, and which we should support), the resource used to list the documents in the `docs.json` file. However, that file only contains the document URI and its associated filter values; it doesn't contain the document title. That means that there's nothing to use to make the link text in the resulting document list, other than the URI itself, which is ugly.

This will considerably increase the size of `docs.json`, so we'll need to watch that, but I don't see any way around it. What do you think @joeytakeda?

**Comment by joeytakeda** [comment]
I agree about a filter only search (I think we've been talking to same person about this :-). And I agree that `docs.json` is the right place to do it. 

The only way around it--which would be a large change, so not necessarily suggesting it, but recording the thought--is to reverse how we understand the filters. Rather than creating a full document JSON, we create a smaller JSONs for each filter value, which lists the documents, their ids, and their titles (i.e. the same structure as what we do for the word tokens). That increases the total size of the output resources, but would probably make filter only searches faster (if only one filter, load that filter document; more than one, just get the union of all of them). I sort of like this solution since it's structurally similar to how we're dealing with the search tokens, but I do see the utility in having the one big `docs.json` (which isn't that big so far for the WEA project, but I can see how it could get big, especially with more complex filters).

**Comment by martindholmes** [comment]
I've been thinking exactly the same thing. It will make any search way more complicated, though. Let's implement the document title thing first, and look at the results for the projects we already have. If we then decide we have to split up the filter JSON, then there's a lot of work in that. 

I haven't been talking to anyone in particular about this; I'm just testing with DVPP, where there are a large number of documents that don't actually have any text, only metadata, so the filter-only search will be essential.

If we do split the filters by name and value, we'll have an issue with dates; I think all the dates will have to be included in a single file, because a search is going to allow ranges, and it won't necessarily be clear what dates are actually available to retrieve.

**Comment by joeytakeda** [comment]
I was thinking DVPP, since I've had a few conversations with them where they've said such a thing would be essential. And now that I think of it, WEA is in precisely the same situation: only about 30% of the documents actually have text, so this will be helpful (and testable) there too. 

Agreed. The splitting of docs.json into filter JSONs can be slated as an improvement once we've got the first stable codebase going. I'll get the titles in the XSLT.

**Comment by joeytakeda** [comment]
Should be implemented in commit https://github.com/projectEndings/staticSearch/commit/0075777d9cc1bb8b8204b49cd56362a80bf25786.

**Comment by martindholmes** [comment]
This is working as expected. I was a little worried to see docTitle as a sibling (so to speak) of other filters in the object structure, meaning that it might be indistinguishable from a filter itself by any code processing filters, but when I looked through the code, I couldn't find anywhere this would cause a problem, since all filter processing is done on the basis of controls already on the page. We might need to watch out for this in future, though.

On the Keats site, docs.json is now only 64K, but that's a relatively small site (and I'm also post-processing the JSON to remove the leading site title from the beginning of all document titles, which cuts the size down a bit. I'll try some work on DVPP as soon as I get a chance; that's going to give us a better indication of practicality. Closing this for now.
