### ISSUE TITLE
Why not link to nearest ancestor fragment id?

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#88]
I've been trying to figure out how we would handle one of the features of the Mariage project's custom search: it can search within divs which represent zones on images, and show fragments of images whose annotations contain the search text. I don't think that's entirely achievable in a generic way, but half of it is: if you have kwic contexts turned on, each context could be accompanied by the id of the nearest ancestor element in the page, so the you could click on a specific kwic and jump to somewhere close to its location in the target page. It's not as good as what we might be able to do if/when the [Text Fragments](https://wicg.github.io/scroll-to-text-fragment/) proposal has general support, but it's the next best thing.

And if/when that standard does have browser support, it's easy to add it to supplement an existing fragment implementation, so that (for example) each of two instances of the same phrase in different parts of the document would get distinct links due to their differing ancestor fragment ids.

**Comment by joeytakeda** [comment]
I’ve had a similar thought before—I think this is a good idea. Would this be nearest *context* ancestor or would it be the nearest ancestor? The reason I ask is that currently all spans (unless otherwise specified) are removed (i.e the tag is removed, but the content remains) in order to minimize the size of the tree in each pass.

So the two options are:

* We use the id of the nearest context ancestor, meaning that all spans continue to be wiped out unless you say it’s a context

* we use the nearest id regardless, meaning that we retain all spans with ids by default unless they’ve been configured as a 0 weight thing.

**Comment by martindholmes** [comment]
@joeytakeda I've just committed some initial work on this. I added some ids to block-level elements in the test dataset, and confirmed that they survive into the tokenized files; and I've added a bit to the function that creates the contexts to confirm that I can retrieve either the nearest ancestor (preferred) or the nearest preceding (next best thing) id. However, that function currently returns a string, so the next stage will have to make it return a sequence, and handle the sequence appropriately. What I've done so far has no impact on anything yet.

Meanwhile, we could simply elect to retain any span which has an id during tokenization, to be sure we don't lose any. How disruptive would that be?

**Comment by joeytakeda** [comment]
Thanks, @martindholmes, for tackling this.  A few thoughts/questions:

1. Should this be configurable? I can imagine that, if you don't have ids in your HTML, or you just have a select few things id'd, then it's not particularly helpful
1. I  think we should do this in the tokenize.xsl rather than json.xsl:
    * We already process all of the `<span>`s to get their positions in tokenize.xsl, and so we could do this in a similar way: process each span, and, if you want to have them link to fragments,  we add `@data-staticSearch-fragment` or whatever which will point to the nearest id
    * Doing that in tokenize would also be less expensive (since we can take advantage of the push structure)
    * And it means that the context function can stay as a regular string function rather than a sequence of strings

**Comment by martindholmes** [comment]
I think if you don't have many ids, then you'll just not get many links next to the contexts in your search outputs (or maybe you'll get links, but they'll just go to the document; we can still use the Google text search link thing without a fragment). I had assumed that it would be each individual context that would need to be linked, but of course it's each individual instance of a term; the context retrieval is not the place to do it. In fact, you could have these links even if you turn off contexts, although it would be a bit weird to have a list of links with nothing distinguishing them.

On the erasure of zero-weighted things, I don't think we should erase the elements with their ids; we should just erase their text content. We still want to be able to link to the nearest preceding id in the document if there's no ancestor id, surely?

**Comment by joeytakeda** [comment]
> In fact, you could have these links even if you turn off contexts, although it would be a bit weird to have a list of links with nothing distinguishing them.

Yep, agreed; even though they don't necessarily have to be, I think the fragment links should be visually tied to the KWIC (i.e. each KWIC item gets a link).

> On the erasure of zero-weighted things, I don't think we should erase the elements with their ids; we should just erase their text content. We still want to be able to link to the nearest preceding id in the document if there's no ancestor id, surely?

I'm a bit wary of changing the zero-weight behaviour as it's crucial in terms of minimizing/simplifying the document sufficiently so that it can be passed through the multi-stage tokenization process. But beyond that, I don't think that a preceding element id is guaranteed to be useful or accurate as a milestone for a term; there's no telling whether or not the preceding thing will actually visually precede the term or if that thing is even rendered by the browser.

But the more I think about this, the more I think that the fragment ids should be a totally opt-in behaviour: without knowing the actual page layout, there's no real way of telling whether or not these fragments are going to be helpful or make sense to end users. Of course, in some cases (like Mariage) where you know that your document ids will guide people to the proper place (or thereabouts), then fragment pointers will be really helpful. But I don't think we can expect that to be true globally since there's no way for us to tell whether or not the nearest id will actually make it easier for people to find the term they were looking for.

**Comment by martindholmes** [comment]
>  I think the fragment links should be visually tied to the KWIC (i.e. each KWIC item gets a link).

That's always been my intention, but where KWICs are not used, perhaps the link would point to the first hit in the document.

I'm fine with this being opt-in, but I think for the vast majority of cases, fragment ids will work fine, and in fact we may encourage people to add useful fragment ids just as they can add meta tags to support more effective searching.

**Comment by martindholmes** [comment]
@joeytakeda How would you like to proceed on this? I'm inclined to leave the work on tokenizing to you, since that's your work primarily, and focus on the JavaScript side, but the need to staticize the Mariage project has suddenly become more urgent because we're transitioning to new VMs which won't support older eXist versions, so if you're overloaded right now I can start in on it. We need:

 - a config setting with documentation (on or off by default?)
 - preservation of fragment ids through tokenization
 - attachment of ids to KWICs in JSON
 - addition of a symbol (what glyph would be best? Unicode U+2693 anchor?)  which is a link to a fragment in JavaScript where there is one in the JSON (which I'll combine with an implementaion of Google's text fragment links while I'm at it).

I think I should reverse my minor change to the JSON, and then create a branch for this and start on it there.

**Comment by joeytakeda** [comment]
>  How would you like to proceed on this? I'm inclined to leave the work on tokenizing to you, since that's your work primarily, and focus on the JavaScript side, but the need to staticize the Mariage project has suddenly become more urgent because we're transitioning to new VMs which won't support older eXist versions, so if you're overloaded right now I can start in on it. 

I don't think should take too long and most of the heavy lifting is in the Javascript, so I'm happy to take this on--I can probably get it to tonight, in fact.

We need:
> 
> * a config setting with documentation (on or off by default?)

While I argued for this to be opt-in, I think we should begin with this on by default just so that we can see what the fallout is for any of the existing projects.

> * preservation of fragment ids through tokenization

Can do. That should be simple enough.

> * attachment of ids to KWICs in JSON

Can do. What do we want this to be called in the JSON? nid? frag? link?

> * addition of a symbol (what glyph would be best? Unicode U+2693 anchor?)  which is a link to a fragment in JavaScript where there is one in the JSON (which I'll combine with an implementaion of Google's text fragment links while I'm at it).

Hmm. That's a good question. I don't love the idea of using a unicode glyph since they render so inconsistently (emojis, etc) and because it won't actually describe what that link is (for a normal user, does an "anchor" really mean link?).

My vote is for adding a short caption (something like "Go to this result") rather than using a glyph and if we were to use a glyph, I'd vote for snagging an SVG from somewhere and using that (i.e. nabbing Bootstrap icon's link, for instance: https://icons.getbootstrap.com/icons/link/), since that will at least be consistent. Alternatively, we could make the entire context item a link:

```
<li>
<a href="document.html#pointer">...something something <mark>term</term> something something...</a>
</li>
```

> I think I should reverse my minor change to the JSON, and then create a branch for this and start on it there.

If you're talking about 9c8f98ee126cf726eabb6e1fbfa11853ab572922, then I'd say it's fine to retain, since you've added anchors to examples etc so it'd probably be more work to revert the change than to simple modify where necessary :-)

**Comment by martindholmes** [comment]
@joeytakeda Re the JSON label, let's keep it short -- fid for fragment id?

I don't think the whole kwic should be a link -- that's ungainly -- and I don't think we want text because people will want to edit that. We're using anchor icons in the TEI Guidelines now, but they are more for anchors than links; LEMDO is experimenting with a little arrow symbol. Many of these symbols work very reliably across browsers, but we'll have to test of course. I don't like the idea of an SVG -- it might appear a hundred times in a page, and it would have to be generated in JavaScript, which is ugly. I think we could go with whatever LEMDO settles on. Re reverting, I didn't mean the whole commit, I just meant reversing the specific change I made to the json.xsl file, which I think you pointed out is not what's needed anyway (although I could be wrong). I'll leave that to you.

**Comment by joeytakeda** [comment]
Over in branch issue88-fragments, I think I've done all of the basic stuff in the XSLT:

- [x] Add a configuration option. I've called the configuration element `<linkToFragment>`; we could call it `linkToNearestFragment`, but that seems. bit long. [An aside: I added the linkToFragment around the `createContexts` element, but it's annoying that order seems to be retained even when `@preserveOrder` is set to false.]
- [x] Add documentation. This is done, but there may be more to do with this. For instance, I didn't know whether we should have a discussion about creating ids and where that should go? For now, I put a bit in the "How do I..." section, but we may want to have a bit more of an expansive discussion (or maybe not?)
- [x] Added handling in `create_config_xsl.xsl`
- [x] Added handling in tokenize.xsl (creating a `@data-staticSearch-fid` attribute) and handling to json.xsl (`<string key="fid">`) 
- [x] Added a diagnostic to flag documents that have no `@id`'d elements in their `<body>`s.  

Now that I've started to implement this, though, I wonder if we should just use the nearest id in document order rather than defaulting to the closest ancestor id (in part, what we're doing isn't finding the "nearest" element in the XPath sense, but the the "closest" per Javascript: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest).

A real life scenario where using ancestor ids by default might be problematic: MoEML's TRIU1: https://mapoflondon.uvic.ca/TRIU1.htm. If you performed a search for `Trumpeter`, you'll get one hit, which is in `//*[@id="TRIU1_Show"]/div[33]` . `#TRIU1_Show` is the closest `id`'d ancestor, so that would be where be the link would point; but, more helpfully, that paragraph is preceded by a page beginning (`#TRIU1_sig_B1v`).

**Comment by martindholmes** [comment]
Thanks @joeytakeda! I've now added handling in the JS (in the branch) to provide links to the fragments after KWICs (where there are fragments). I used the little arrow symbol that LEMDO is probably going to use to form the link.

I think we've talked before about the options with regard to nearest-ancestor versus nearest-preceding-id-in-document-order. I like the latter better, BUT it will screw things up if we combine it with Google's scroll-to-text-fragment (which I plan to add this morning); as far as I understand it, if you combine a fragment id with a text-search bit, it will search for that text inside the fragment. If that's the case, then I think nearest-ancestor is the way to go. I'll read the [spec](https://wicg.github.io/scroll-to-text-fragment/) more carefully today.

**Comment by martindholmes** [comment]
I've now added scroll-to-text-fragment support, and it seems to be working well in both Chromium and Chrome; I'll test on Edge at some point. I initially thought we could use the prefix and suffix components of the spec to make a finely-tuned URL, but that's problematic because of the leading and trailing ellipsis characters, as well as the fact that some things in the KWIC string are not necessarily exactly as they appear in the text (q elements in the text may be turned into straight quotes in the KWIC string, for example). But I think the combination of a fragment identifier and a test string is already pretty well-tuned, and it should be enough for most purposes.

**Comment by martindholmes** [comment]
Works on Edge for Linux too. Doesn't work on Opera.

**Comment by joeytakeda** [comment]
I've just given it a test using our standard test set as well as the `emod` stuff (i.e. `ant -Dconfig=config_emod.xml`) since that's quick but also a decent subset of documents. 

Since the spec is still so nascent, I think there are still some bugs in Chrome:

* I think the hash handling doesn't actually work, at least in Chrome 87.0.4280.88. For instance, a search for "Oxford" in the emod texts produces this for MONU1 (indented here for convenience):

```html
      <ul class="kwic">
            <li>...of Linox, the Earles of Nottingham, Suffolke, Arundel, <mark>Oxford</mark>, Worceſter, Pembrooke, Eſſex, Northampton, Saliſbury, Montgomery, the...
            <a href="MONU1.htm#MONU1_d2e2047_2:~:text=Oxford" class="fidLink">↬</a></li>
            <li>went to <mark>Oxford</mark> and ſurueighing all the grounds, in and...
            <a href="MONU1.htm#MONU1_d2e2389_2:~:text=Oxford" class="fidLink">↬</a></li>
            <li>...riding one day out at the North-Gate at <mark>Oxford</mark>, he ſpied on his right hand the...
            <a href="MONU1.htm#MONU1_d2e2389_2:~:text=Oxford" class="fidLink">↬</a></li>
        </ul>
```
The first hit specifies a different hash than the other two, but, for me at least, they all scroll and highlight the same bit in `#MONU1_d2e2047_2`.

* In any case, even if that did work (i.e. the first link and the second link going to two distinct places), the third link going to the same place as the second (when the second went to a different place than the first) would be confusing to end-users: the first two links went exactly where you wanted while the last one didn't for completely opaque reasons.

* The text fragment break hash handling in all other browsers. In Firefox (82.0.3) and Safari (14610.2.11.51.10),  the link  `MONU1.htm#MONU1_d2e2389_2:~:text=Oxford` directs the user to the top of the page, and not #MONU1_d2e2389_2. 

So I'm fairly wary about baking in the text fragment stuff since it's so embryonic...

**Comment by martindholmes** [comment]
You're right, it does break hash handling, which is very weird; I'll take another look at the spec and see if I've misunderstood something, but I don't think so. The issue of which text gets highlighted is what I was talking about above: if you don't include a prefix and a suffix, then of course it highlights the first instance of that text in the section mentioned, but we can't massage our KWICs into prefixes and suffixes because they're not true representations of the text that's in the page.

However, we might be able to obviate all this if we can determine whether the browser supports the feature or not. Looking into that now.

**Comment by martindholmes** [comment]
Yes, we can determine whether the browser supports it by using document.fragmentDirective, so we can suppress it when not supported. Also, we could look at the possibility of parsing out the first and last words of the entire KWIC, and using those as the textStart and textEnd parameters; that might make the hit more likely to be unique (although it could make it less likely, if the words were "the" and "a", of course).

**Comment by martindholmes** [comment]
I've added feature detection, which solves the fragment issue for non-supporting browsers, in commit #8b42206. We still have the issue that the browser can't distinguish between multiple instances of the same word in the same fragment. Options are:

1. Go back to trying to figure out a decent prefix and suffix to distinguish between hits with different contexts. That may require that we rethink the way our KWICs are generated.
2. Check each KWIC link and if it's no different from one earlier in the list, simply drop it.

However, it's perfectly possible that a nested structure with hierarchical ids could result in two different links which nevertheless end up pointing to the same string of text; if the first hit is inside a child with an id, and the second is after that child, then the first hit will end up being highlighted in both cases because it's the first instance of the text inside both the parent and the ancestor, even though the links are technically different.

**Comment by martindholmes** [comment]
I can confirm that in Chrome at least, the combination of a fragment id with a text-fragment does not work; the fragment id is completely ignored as far as I can tell. In the test data, if you search for "love" you can see this clearly, because in the Twilight poem each line has its own id, and although the ids appear clearly in the links, the browser only highlights the initial instance of "love".

Therefore, for this to work reliably, I think we'll need to find a way to make the entire KWIC into a text-fragment. I'm going to do some experimentation on that.

**Comment by joeytakeda** [comment]
I've done a bit more research on the hash thing, and it looks like the hash issue I specified above isn't actually a bug, but something that they're still considering:

https://github.com/WICG/scroll-to-text-fragment/issues/55
https://github.com/WICG/scroll-to-text-fragment/issues/75

So we would need to do the prefix and suffix stuff, but I'm wary of going through all sorts of hoops to add support for an experimental, non-standardized technology that is supported only by Google and whose syntax is liable to change as things move forward--this seems a boutique solution and contradictory to Endings principles. 

I think if we really do want inline text highlighting for a document, then we really should just do that and write our own, since that would be much more stable and reliable and, crucially, be standards compliant. For now, though, I think we should just link to the nearest ancestor fragment and not do the text fragment stuff--while it might not be as helpful, the results at the very least will be consistent.

**Comment by martindholmes** [comment]
Point taken, but since we can do feature-detection already anyway, we're not breaking anything; any browser that doesn't support this will just use the plain fragment id. A custom solution requires that JS run in the target pages on the site, and while that's doable for some of our sites, it's not for others. I think a better option might be to have this feature turned off by default, with a warning that it's experimental, and track the Google spec development for a little while in case it changes. 

But we do need to figure out how to turn the full KWIC into a text-fragment. The only barrier to that I'm seeing right now is that for some reason, the tokenizer turns curly quotes into straight quotes when it generates the KWIC (at least, I assume that's what's happening, because the source page has curly quotes and the KWIC has straight quotes, escaped, in the JSON). If the quotes match what's in the original text, and if the leading character is a word character (so the whole KWIC doesn't start with a quote), it seems to work. Luckily we have thorny examples to work with in our test data, otherwise I might not have noticed the problem.

**Comment by martindholmes** [comment]
It's the template at line 390 of tokenize.xsl that normalizes all the quote marks. That will prevent us from creating accurate text fragments for text runs containing quotations/apostrophes. The various quote marks seem to be replaced with $straightDoubleApos, which is then used in all the regular expressions used to tokenize the content. I wonder if we could just leave those various quote marks in place, and just account for them in the tokenizing regexes? It would slightly reduce the size of some JSON files (no need to escape curly quotes) and make a full text fragment possible, removing all the ambiguity.

**Comment by joeytakeda** [comment]
>  think a better option might be to have this feature turned off by default, with a warning that it's experimental, and track the Google spec development for a little while in case it changes.

Yes, that seems like a good idea. Should that be in the config, or just an option to pass to the staticSearch object? (I think the latter)

> The various quote marks seem to be replaced with $straightDoubleApos, which is then used in all the regular expressions used to tokenize the content. I wonder if we could just leave those various quote marks in place, and just account for them in the tokenizing regexes?

Yes, agreed that this is a good thing to do anyway. 

Now that I look at this, though, I notice that there's a bug in the XSLT tokenizer: single quotation marks aren't included in the word regex. So something like "O'Mally" is stemmed as if it is "Mally", but if you type in `O'Mally` into the search box, it just removes the apostrophe. Notice the difference between a search for `Mally` versus `O'Mally` versus `"O'Mally"`:

https://winnifredeatonarchive.org/search.html?q=Mally
https://winnifredeatonarchive.org/search.html?q=O%27Mally
https://winnifredeatonarchive.org/search.html?q=%22O%27Mally%22

So I suppose what we'll need to do here is add all apostrophes to the token regex so that all quotation marks are included in a word and then remove them before tokenizing ((`J"oh”n`, `s’prize`, `you'll`) => (`John`, `sprize`, `youll`))

**Comment by martindholmes** [comment]
> > think a better option might be to have this feature turned off by default, with a warning that it's experimental, and track the Google spec development for a little while in case it changes.
> 
> Yes, that seems like a good idea. Should that be in the config, or just an option to pass to the staticSearch object? (I think the latter)

I think the former, actually, because some people may wish to turn it off anyway, even if it's widely adopted. I don't know why they would, but they might. And if we're going to pass an option to the staticSearch object, that's best done from the config anyway; lots of people will struggle to get the JavaScript right if they have to do it themselves.

> > The various quote marks seem to be replaced with $straightDoubleApos, which is then used in all the regular expressions used to tokenize the content. I wonder if we could just leave those various quote marks in place, and just account for them in the tokenizing regexes?
> 
> Yes, agreed that this is a good thing to do anyway.
> 
> Now that I look at this, though, I notice that there's a bug in the XSLT tokenizer: single quotation marks aren't included in the word regex. So something like "O'Mally" is stemmed as if it is "Mally", but if you type in `O'Mally` into the search box, it just removes the apostrophe. Notice the difference between a search for `Mally` versus `O'Mally` versus `"O'Mally"`:
> 
> https://winnifredeatonarchive.org/search.html?q=Mally
> https://winnifredeatonarchive.org/search.html?q=O%27Mally
> https://winnifredeatonarchive.org/search.html?q=%22O%27Mally%22

Yes, I've noticed this before; I think we discussed it at one point. It's never easy to determine whether a trailing apostrophe is a plural possessive (which I think makes it part of the word) or a punctuation mark (which doesn't), but when it's internal to the word, it should definitely be retained. We may find ourselves in a situation in which searching for a word containing an apostrophe is difficult because you won't necessarily know which apostrophe to search for, but the JS engine could silently expand a word-internal apostrophe into both options, I suppose.

> 
> So I suppose what we'll need to do here is add all apostrophes to the token regex so that all quotation marks are included in a word and then remove them before tokenizing ((`J"oh”n`, `s’prize`, `you'll`) => (`John`, `sprize`, `youll`))

We can't remove it from "you'll", though; word-internal single apostrophes should be retained, I think. Don't you? We might elect to do something at the stemmer level about these forms, but for the purposes of the tokenizer (where we get the KWICs from), we should keep them.

**Comment by martindholmes** [comment]
I can now see perfectly well why you might want to turn off text fragments: any site that runs JS on page load which messes with the URL will have no use for them; and any page which hides some content by default will not work if the hidden content includes the text fragment. Keats has JS that runs on load (added to mimic some cosmetic behaviour from a previous incarnation of the site), so I would turn it off there.

I've also noticed that linking to text fragments is virtually pointless in the case of a single word link, because of the issue of multiple hits, but it's very effective in the case of phrasal searches, where phrases are likely to occur fewer times in the results. Should we restrict its use to phrasal searches, and leave fragments to do the rest? (Of course, you can quote a single word, which would confuse the issue a bit.)

I also agree that we should _make it feasible_ to supply  JS code in your own pages that would highlight hits -- again, controlled by a setting you can turn on if you want it -- by supplying the search string as a query string to the page URL. We might even supply a sample implementation. But of course it's remarkably difficult to do properly, given that stemming is involved, and text strings may cross element boundaries.

**Comment by joeytakeda** [comment]
> I've also noticed that linking to text fragments is virtually pointless in the case of a single word link, because of the issue of multiple hits, but it's very effective in the case of phrasal searches, where phrases are likely to occur fewer times in the results. Should we restrict its use to phrasal searches, and leave fragments to do the rest? (Of course, you can quote a single word, which would confuse the issue a bit.)

Yes, I think that makes sense to restrict it to phrasal searches since it stands the best chance of being accurate; if the spec ever ends up including some way of specifying instances of a hit, then we can revisit MAY CONTAIN searches later.

> I also agree that we should make it feasible to supply JS code in your own pages that would highlight hits -- again, controlled by a setting you can turn on if you want it -- by supplying the search string as a query string to the page URL. We might even supply a sample implementation. But of course it's remarkably difficult to do properly, given that stemming is involved, and text strings may cross element boundaries.

Yes, I think the option of adding a query parameter is a good idea. I had a very basic implementation of this in my prototype of staticSearch for the Winnifred Eaton Archive--I don't think it exists anymore in my actual code, but I'll look in the history and see if there's anything worth keeping. I had it set up so that staticSearch would add a query parameter to docLink that specified the token files pipe separator:

```
document.html?terms=foo|bar|blort
```

Then some Javascript in document.html would 

* parse the query parameter and retrieve the token JSONs
* For each token json, find the document and collect all of the unique forms in that document
* Then do a very crude look up across the document collection for instances of those forms, adding a `<mark>` around them

All of the WEA texts have a toolbar on the lefthand side, so I was also able to provide a bit of navigation (go to next hit, previous hit, etc) since there was an convenient place to put those controls.

**Comment by martindholmes** [comment]
On the issue of supporting custom JS highlighting, what I'm thinking is that we should just add the existing querystring from the search page URL to the hit links; that contains all the information about what you searched for, and so any cunning code you come up with will have full access to any info it needs. But I think that's a separate ticket.

I've changed my mind about scroll-to-text-fragment being limited to phrasal searches -- it should use entire KWICs. For this ticket/branch, this is what I propose:

 - Fragment ids are on by default (as now). (I keep meaning to check that we're not pulling the body id if it happens to be the nearest -- that would be pointless.) Perhaps the current config item "linkToFragment" should be "linkToFragmentId" for clarity.
 - Scroll-to-text-fragment is controlled by a config setting called "scrollToTextFragment", which is off by default, and comes with plenty of warnings and links to the spec and various criticisms of it. 
 - The tokenizer should be rejigged so that it doesn't normalize quotations and apostrophes; that would ensure that full KWICs survive intact, and can be turned into text-fragment pointers.

If we get the last bit right, then every text-fragment pointer will consist of a long and unambiguous KWIC, which should solve the problem of single-word instances. What do you think?

**Comment by joeytakeda** [comment]
> * Fragment ids are on by default (as now). (I keep meaning to check that we're not pulling the body id if it happens to be the nearest -- that would be pointless.) Perhaps the current config item "linkToFragment" should be "linkToFragmentId" for clarity.

Yes, that sounds good. Right now, the fragment ids don't have any sanity checking other than not to use the root id, but we should extend that sanity checking. In fact, we should probably make it a bit more generic to guard against cases where some wrapper element has an id that surrounds everything, like:

```html
<body id="body">
<div id="container">
<!--All content here-->
</div>
</body>

Since we add the `fid` in the tokenizing step, we can check this in the JSON by looking at the spans and making sure there are at least 2 distinct fragment ids; if there isn't, then it makes no sense to link any of them. 

> * Scroll-to-text-fragment is controlled by a config setting called "scrollToTextFragment", which is off by default, and comes with plenty of warnings and links to the spec and various criticisms of it.'

That sounds good to me. 

> * The tokenizer should be rejigged so that it doesn't normalize quotations and apostrophes; that would ensure that full KWICs survive intact, and can be turned into text-fragment pointers.
> 
> If we get the last bit right, then every text-fragment pointer will consist of a long and unambiguous KWIC, which should solve the problem of single-word instances. What do you think?

Now that I think about this a bit more, I've realized that the bigger issue is that anything specified to be ignored using `<rule weight="0" />` is removed from the document prior to indexing and so it doesn't appear in the KWIC, but could easily be in the running text of the document: footnote markers, for instance. So I'm not sure what the right way around that would be.

**Comment by martindholmes** [comment]
I don't think we expect this thing to work 100% of the time -- Google doesn't either, from reading around their spec and their list of issues. It's just that most of the time it probably will, and when it does, it'll be a great blessing. So I think we just do the best we can and produce KWICs that are not arbitrarily different from the source, accepting that they may end up being different from the source due to things like ignored bits.

**Comment by joeytakeda** [comment]
Commit https://github.com/projectEndings/staticSearch/commit/abf18ae05f4a4be9efe6311202395c02ec7984b4 removes the normalization of quotation marks from strings, so that should be fixed; the single apostrophe issue remains, though, since I wasn't sure what we wanted to do. I'm going to move that to a new ticket, though, since that is now just a tokenizing/stemming issue.  

Also double checked the body id stuff. Right now, the process uses any id below the body (but not on the body itself), so that should be fine. My plan to have a better sanity check is a fools errand, really: even if all of the tokens have the same ancestor id, there's no way to know whether or not that might actually be helpful (if there's a big image at the top of the page, for instance, which pushes all of the text below the initial viewport). So the HTML/body check should be good enough.

**Comment by martindholmes** [comment]
Thanks, that's perfect! I'll rewrite tomorrow to use the whole KWIC for scroll-to-text-fragment and we'll see what the success rate is.

You're absolutely right about the ids; the only one that's pointless is the body.

**Comment by martindholmes** [comment]
All implemented and tested; as far as I can tell, it works pretty reliably, although when text strings cross particular element boundaries it fails (as expected). Anyway, with the revisions to the tokenization process, quotes and the like no longer confuse it, so I would expect a lot of instances to work pretty well. There may be some tuning we can do -- for example, we could trim KWICs down to e.g. six words to get a good balance between uniqueness and fragility. But that can wait till we see how it's working in e.g. MoEML and Scancan. I'll do a pull request now.

**Comment by joeytakeda** [comment]
Now merged, but re-opening until we've tested with all of the projects--I've kicked off builds of WEA and LOI (which overrides resultsAsHtml) so we'll see if there are any issues there.

**Comment by martindholmes** [comment]
Scancan also overrides SSResultSet~resultsAsHtml, and it worked without changes to the override. I've now re-done the override once, and I'll have to re-do it again now resultsAsHtml has changed, to enable the feature, but it should work fine. I've turned it on for MoEML too.

**Comment by martindholmes** [comment]
There's one outstanding bug that I need to fix: the trailing truncation string (the ellipsis) is not being stripped from the KWIC, so scroll-to-text-fragment is actually not working yet. This must be a regression for some reason, because I had it working before. Testing in Graves shows the problem.

**Comment by martindholmes** [comment]
@joeytakeda I think this is working pretty well now, as tested in Graves and Colonial Despatches as well as Scancan; these are my main candidates for the experimental scroll-to-text-fragment. The pure fragment stuff is working well in MoEML, and I see highlighted hits in WEA too. Any reason not to close this now?

**Comment by joeytakeda** [comment]
Yep! This seems good to close now; if I notice any other bugs, those can be new tickets. Closing this now.
