### ISSUE TITLE
Punctuation shouldn't be stripped from phrasal searches

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#98]
Arising out of the work for #95 , I was trying to test if `"o'clock, O'Reilly"` would work as a phrase, and noticed that all punctuation (except apostrophes) is stripped from exact phrases. So `"o'clock, O'Reilly"` returns no hits, even though it does exist as that exact phrase in the document. 

I couldn't find any documentation as to whether that was the intended behaviour or not. @martindholmes do you recall, if this was an intentional thing, the rationale behind that?

**Comment by martindholmes** [comment]
This is definitely something that needs revisiting. This is the relevant code:

https://github.com/projectEndings/staticSearch/blob/4e146ac28399b4a844d5f86e10271ec0cb800e30/js/ssSearch.js#L662

and the rationale behind it was to generate token sequences which would be appropriate input to the stemmer. Punctuation shouldn't be stripped from inside phrases, for sure, and apostrophes should not be stripped or normalized at this stage; I now believe it should happen in the stemmer (so it would never happen for phrases at all). The problem is that you can't be sure what constitutes a phrasal search until you've processed the search box input, and that input can be anything. Let's make this part of the branch you're currently working on, and rethink the handling of apostrophes entirely.

**Comment by joeytakeda** [comment]
As a bit of house keeping and for better record keeping, I've changed the title from a question to a statement and set the milestone to 1.1.

**Comment by joeytakeda** [comment]
And this is now fixed with #105 so closing.
